import { expect, test } from "bun:test";
import { createHash } from "node:crypto";
import { outputPaths } from "../src/folder/outputs";
import { presetProfile } from "../src/folder/presets";
import { renderOutputs } from "../src/folder/preview";
import { instructionTemplateRevision } from "../src/folder/render";
import { activatableTools } from "../src/tools/catalog";
import { bindings } from "./fixtures/machine-bindings";

// The template revision names the bytes of the generated Folder (decision
// F14). A Folder records the revision and the digests of what it rendered;
// within one revision the planner requires the recorded digests to be what
// this product renders, and only an older revision is re-rendered as an
// upgrade. Changing generated bytes without a new revision therefore refuses
// every existing Folder with `incomplete-state` (issue #133, v0.1.8-rc.14).
//
// This pin is the guard: the digest of every output of a fixed set of
// compositions, for the current revision. When the generated text changes,
// bump `instructionTemplateRevision` and pin the new digest here together
// with the new revision; never update the digest under the same revision.
// `bun test -u` does not touch it. The fixtures in `tests/fixtures` feed the
// compositions too.
const pinned = {
  revision: "base-instructions-19",
  digest: "9d212c99256aeee704b6292de7c6f788c32296a29e7ca40c86ac190aef36f4ef",
} as const;

const optionalTools = activatableTools()
  .filter((entry) => entry.activation.tier !== "required")
  .map((entry) => entry.name)
  .sort();

// Every preset on every OS it is offered for, with and without recorded
// peers, in both languages; once with the preset's defaults and nothing
// enabled, once with the other communication axes, every optional catalog
// tool and a note.
const environments = [
  { preset: "local", machine: null, os: "windows" },
  { preset: "local", machine: null, os: "macos" },
  { preset: "hosted-personal", machine: bindings.personal, os: "linux" },
  { preset: "hosted-personal", machine: bindings.personalRelated, os: "linux" },
  {
    preset: "hosted-organization-personal",
    machine: bindings.organization,
    os: "linux",
  },
  {
    preset: "hosted-organization-personal",
    machine: bindings.related,
    os: "linux",
  },
  { preset: "hosted-organization-team", machine: bindings.team, os: "linux" },
  {
    preset: "hosted-organization-steward",
    machine: bindings.automated,
    os: "linux",
  },
] as const;

function compositions() {
  const all = [];
  for (const environment of environments)
    for (const locale of ["cs", "en"] as const) {
      all.push({
        preset: environment.preset,
        machine: environment.machine,
        profile: presetProfile(environment.preset, environment.os, { locale }),
        tools: [],
        toolNotes: {},
      });
      all.push({
        preset: environment.preset,
        machine: environment.machine,
        profile: presetProfile(environment.preset, environment.os, {
          locale,
          detail: "technical",
          coordination: "coordinator",
        }),
        tools: optionalTools,
        toolNotes: { [optionalTools[0] ?? "gh"]: "Use it for the example." },
      });
    }
  return all;
}

function renderedDigest(): string {
  const hash = createHash("sha256");
  for (const [index, composition] of compositions().entries()) {
    const outputs = renderOutputs(composition);
    hash.update(`${index}\0`);
    for (const path of outputPaths) hash.update(`${path}\0${outputs[path]}\0`);
  }
  return hash.digest("hex");
}

test("the pinned rendered digest belongs to the current template revision", () => {
  if (instructionTemplateRevision !== pinned.revision)
    throw new Error(
      `instructionTemplateRevision is ${instructionTemplateRevision}, the pin is for ${pinned.revision}: pin the digest this revision renders, ${renderedDigest()}`,
    );
  expect(compositions().length).toBe(environments.length * 4);
});

test("the generated Folder renders the bytes pinned for the current template revision", () => {
  const digest = renderedDigest();
  if (digest !== pinned.digest)
    throw new Error(
      `generated Folder text changed; bump instructionTemplateRevision and update this digest (${pinned.revision} pins ${pinned.digest}, the outputs render ${digest})`,
    );
  // Rendering is deterministic: the same compositions, the same bytes.
  expect(renderedDigest()).toBe(digest);
});
