import { afterAll, beforeAll, expect, test } from "bun:test";
import {
  copyFile,
  mkdir,
  mkdtemp,
  readdir,
  readFile,
  realpath,
  rm,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { runReleaseKeys } from "../scripts/release-keys";
import { runReleasePublish } from "../scripts/release-publish";
import { DistributionTransport } from "../src/distribution/transport";
import type { UpdateChannel } from "../src/update/channel";
import { checkForUpdate } from "../src/update/check";
import { runUpdateCommand } from "../src/update/cli";
import { readChannel } from "../src/update/config";
import { trustRootDefines } from "../src/update/defaults";
import { identityDefines } from "../src/update/identity";
import { performUpdate } from "../src/update/update";
import {
  commit,
  identityOf,
  installVersion,
  type ProductBinary,
  productBinary,
  target,
} from "./helpers/update-product";

/** The publisher and the REAL client against each other. The tree the
 * publisher writes is served as static files on loopback — what GitHub Pages
 * does — and release assets are served by a second loopback origin that
 * answers with a redirect to a third one — what GitHub Releases does. Keys
 * are generated by the key tool into a temporary directory and die with it.
 */
const clock = () => new Date();
let work: string;
let tree: string;
let keys: string;
let rootFile: string;
let pages: ReturnType<typeof Bun.serve>;
let releases: ReturnType<typeof Bun.serve>;
let storage: ReturnType<typeof Bun.serve>;
/** Serve these bytes as `timestamp.json`: a CDN that still holds an old one. */
let cachedTimestamp: Buffer | undefined;
const assets = new Map<string, Buffer>();

beforeAll(async () => {
  work = await realpath(await mkdtemp(join(tmpdir(), "publish-journey-")));
  tree = join(work, "tree");
  keys = join(work, "keys");
  rootFile = join(work, "release-root.json");
  await mkdir(tree);
  for (const role of ["root", "targets", "snapshot", "timestamp"])
    expect(
      (await runReleaseKeys(["generate", "--role", role, "--out", keys])).code,
    ).toBe(0);
  expect(
    (
      await runReleaseKeys([
        "init-root",
        "--root-key",
        join(keys, "root.private.pem"),
        "--targets",
        join(keys, "targets.public.json"),
        "--snapshot",
        join(keys, "snapshot.public.json"),
        "--timestamp",
        join(keys, "timestamp.public.json"),
        "--out",
        rootFile,
      ])
    ).code,
  ).toBe(0);
  pages = Bun.serve({
    hostname: "127.0.0.1",
    port: 0,
    async fetch(request) {
      const path = decodeURIComponent(new URL(request.url).pathname);
      if (path.includes("..")) return new Response("refused", { status: 400 });
      if (path === "/metadata/timestamp.json" && cachedTimestamp)
        return new Response(new Uint8Array(cachedTimestamp));
      const file = Bun.file(join(tree, path));
      return (await file.exists())
        ? new Response(file)
        : new Response("not found", { status: 404 });
    },
  });
  storage = Bun.serve({
    hostname: "127.0.0.1",
    port: 0,
    fetch(request) {
      const bytes = assets.get(new URL(request.url).pathname);
      return bytes
        ? new Response(new Uint8Array(bytes))
        : new Response("not found", { status: 404 });
    },
  });
  releases = Bun.serve({
    hostname: "127.0.0.1",
    port: 0,
    fetch(request) {
      const path = new URL(request.url).pathname;
      return assets.has(path)
        ? new Response(null, {
            status: 302,
            headers: { location: `${storage.url.origin}${path}?signature=x` },
          })
        : new Response("not found", { status: 404 });
    },
  });
});

afterAll(async () => {
  await pages?.stop(true);
  await releases?.stop(true);
  await storage?.stop(true);
  await rm(work, { recursive: true, force: true });
});

const publish = (args: string[]) =>
  runReleasePublish(
    [...args, "--tree", tree, "--root", rootFile, "--keys-dir", keys],
    { env: {} },
  );

/** What the release workflow hands to `add-release`: the build's executable
 * and its `identity.json` per target, named like the release assets.
 */
async function release(
  binary: ProductBinary,
  hosting: "tree" | "release-asset",
) {
  const directory = join(work, `assets-${binary.version}`);
  await mkdir(directory);
  await copyFile(binary.path, join(directory, `lazurio-${target}`));
  await writeFile(
    join(directory, `lazurio-${target}.identity.json`),
    JSON.stringify({
      kind: "unsigned-development-candidate",
      identity: identityOf(binary),
    }),
  );
  const notes = join(directory, "notes.md");
  await writeFile(notes, `## What's changed in ${binary.version}\n`);
  const base = `/example/product/releases/download/v${binary.version}/`;
  if (hosting === "release-asset")
    assets.set(`${base}lazurio-${target}`, binary.bytes);
  return publish([
    "add-release",
    "--channel",
    "preview",
    "--version",
    binary.version,
    "--notes-file",
    notes,
    "--assets-dir",
    directory,
    ...(hosting === "release-asset"
      ? [
          "--asset-url-base",
          `${releases.url.origin}${base}`,
          "--loopback-fixture",
        ]
      : []),
  ]);
}

async function machine(channel: UpdateChannel, origins?: string[]) {
  const base = join(
    await realpath(await mkdtemp(join(work, "machine-"))),
    "base",
  );
  const installed = await productBinary("1.0.0");
  await installVersion(base, installed);
  const transport = new DistributionTransport(
    origins ?? [pages.url.origin, releases.url.origin, storage.url.origin],
    60_000,
    new AbortController().signal,
    true,
  );
  const input = async () => ({
    base,
    metadataBaseUrl: `${pages.url}metadata/`,
    targetBaseUrl: `${pages.url}targets/`,
    channel,
    identity: { version: "1.0.0", commit, target },
    // The compiled-in root: offered on every run, used only for first trust.
    embeddedRoot: await readFile(rootFile),
    transport,
    clock,
    lockTimeoutMs: 10_000,
  });
  return {
    base,
    check: async () => checkForUpdate(await input()),
    download: async () => {
      return performUpdate({
        ...(await input()),
        service: { kind: "none" },
        openRange: (url, offset, signal) =>
          transport.openRange(url, offset, signal),
        downloadOnly: true,
        downloadPolicy: { backoffMs: 1, stalledAttempts: 2 },
      });
    },
    trustedRootVersion: async () =>
      JSON.parse(await readFile(join(base, "trust", "root.json"), "utf8"))
        .signed.version as number,
  };
}

test("publish A, the client downloads it; publish B as a release asset behind a signed URL; promote; rotate the root — one repository, the real client", async () => {
  const a = await productBinary("1.1.0");
  const b = await productBinary("1.2.0");

  // A: everything inside the static tree.
  expect(await release(a, "tree")).toMatchObject({ code: 0 });
  const preview = await machine("preview");
  expect(await preview.check()).toMatchObject({
    kind: "available",
    version: "1.1.0",
    artifactSha256: a.sha256,
    sequence: 1,
  });
  expect(await preview.download()).toEqual({
    kind: "ready",
    version: "1.1.0",
    staged: a.name,
  });
  const staged = (base: string, binary: ProductBinary) =>
    readFile(join(base, "versions", binary.name, "lazurio"));
  expect((await staged(preview.base, a)).equals(a.bytes)).toBe(true);
  // Nothing was promoted: `stable` has no document yet.
  const stable = await machine("stable");
  expect(await stable.check()).toMatchObject({
    kind: "error",
    code: "channel-invalid",
    context: { reason: "absent" },
  });
  const timestampOfA = await readFile(join(tree, "metadata/timestamp.json"));

  // B: the executable is a release asset; only its signed URL is in the tree.
  expect(await release(b, "release-asset")).toMatchObject({ code: 0 });
  expect(
    (await readdir(join(tree, "targets/artifacts", b.sha256))).sort(),
  ).toEqual([expect.stringMatching(/\.identity\.json$/)]);
  // What the release workflow does before it publishes: download every
  // selected artifact through the client's transport. A release host that
  // redirects to an origin outside the list stops the release.
  expect(
    await publish([
      "verify",
      "--loopback-fixture",
      "--artifact-origin",
      releases.url.origin,
    ]),
  ).toMatchObject({
    code: 1,
    stderr: expect.stringContaining("Refused: unreachable"),
  });
  expect(
    await publish([
      "verify",
      "--loopback-fixture",
      "--artifact-origin",
      releases.url.origin,
      "--artifact-origin",
      storage.url.origin,
    ]),
  ).toMatchObject({ code: 0 });
  expect(await preview.check()).toMatchObject({
    kind: "available",
    version: "1.2.0",
    artifactSha256: b.sha256,
    sequence: 2,
  });

  // The redirect target of a release asset must be a listed origin. A
  // transport that knows the repository and the release host, but not where
  // the release host redirects to, refuses — and leaves nothing behind.
  const narrow = await machine("preview", [
    pages.url.origin,
    releases.url.origin,
  ]);
  expect(await narrow.download()).toMatchObject({
    kind: "error",
    code: "network-unavailable",
    context: { resource: "artifact" },
  });
  expect(await readdir(join(narrow.base, "versions"))).toEqual([
    (await productBinary("1.0.0")).name,
  ]);
  expect(await preview.download()).toEqual({
    kind: "ready",
    version: "1.2.0",
    staged: b.name,
  });
  expect((await staged(preview.base, b)).equals(b.bytes)).toBe(true);

  // Promotion: `stable` now offers exactly the bytes `preview` offered.
  expect(await publish(["promote", "--version", "1.1.0"])).toMatchObject({
    code: 1,
    stderr: expect.stringContaining("version-mismatch"),
  });
  expect(await publish(["promote", "--version", "1.2.0"])).toMatchObject({
    code: 0,
  });
  expect(await stable.check()).toMatchObject({
    kind: "available",
    version: "1.2.0",
    artifactSha256: b.sha256,
    sequence: 1,
  });
  expect(await stable.download()).toMatchObject({
    kind: "ready",
    staged: b.name,
  });

  // Retention: somebody still served the timestamp of A — a CDN cache — gets a
  // COMPLETE older repository: snapshot, targets, document, identity, bytes.
  cachedTimestamp = timestampOfA;
  try {
    const behind = await machine("preview");
    expect(await behind.check()).toMatchObject({
      kind: "available",
      version: "1.1.0",
    });
    expect(await behind.download()).toMatchObject({
      kind: "ready",
      staged: a.name,
    });
  } finally {
    cachedTimestamp = undefined;
  }

  // Root rotation: a new root key AND a new targets key, made offline by the
  // key tool, installed by a refresh. A Machine that trusts root 1 walks the
  // chain with its own trust code and keeps updating.
  const next = join(work, "keys-next");
  for (const role of ["root", "targets"])
    await runReleaseKeys(["generate", "--role", role, "--out", next]);
  expect(await stable.trustedRootVersion()).toBe(1);
  expect(
    (
      await runReleaseKeys([
        "rotate-root",
        "--current",
        rootFile,
        "--root-key",
        join(keys, "root.private.pem"),
        "--new-root-key",
        join(next, "root.private.pem"),
        "--targets",
        join(next, "targets.public.json"),
        "--out",
        join(work, "root-2.json"),
      ])
    ).code,
  ).toBe(0);
  // The old targets key can no longer sign; nothing is written.
  const rotate = (keysDirectory: string) =>
    runReleasePublish(
      [
        "refresh",
        "--tree",
        tree,
        "--root",
        join(work, "root-2.json"),
        "--keys-dir",
        keysDirectory,
      ],
      { env: {} },
    );
  expect(await rotate(keys)).toMatchObject({
    code: 1,
    stderr: "Refused: key-unauthorized (targets)",
  });
  await copyFile(
    join(keys, "snapshot.private.pem"),
    join(next, "snapshot.private.pem"),
  );
  await copyFile(
    join(keys, "timestamp.private.pem"),
    join(next, "timestamp.private.pem"),
  );
  expect(await rotate(next)).toMatchObject({ code: 0 });
  expect(await stable.check()).toMatchObject({
    kind: "available",
    version: "1.2.0",
  });
  expect(await stable.trustedRootVersion()).toBe(2);
  // A Machine installed before the rotation, whose executable embeds root 1.
  expect(await (await machine("stable")).check()).toMatchObject({
    kind: "available",
    version: "1.2.0",
  });
}, 120_000);

test("switching the channel is explicit, persisted in update/config.json, tolerant of damage, and never offers a lower version", async () => {
  const base = join(
    await realpath(await mkdtemp(join(work, "channel-"))),
    "base",
  );
  const run = (args: string[], version: string) =>
    runUpdateCommand([...args, "--base", base], {
      identity: { version, commit, target },
      clock,
    });
  expect(await readChannel(base)).toBe("stable");
  expect(await run(["channel"], "1.0.0")).toMatchObject({
    code: 0,
    stdout: "Channel: stable",
  });
  expect(await run(["channel", "nightly"], "1.0.0")).toMatchObject({ code: 2 });
  expect(await run(["channel", "preview", "--json"], "1.0.0")).toEqual({
    code: 0,
    stdout: '{"channel":"preview"}',
    stderr: "",
  });
  expect(
    JSON.parse(await readFile(join(base, "update", "config.json"), "utf8")),
  ).toEqual({ schemaVersion: 1, channel: "preview" });
  await writeFile(join(base, "update", "config.json"), "{ damaged");
  expect(await readChannel(base)).toBe("stable");
  await writeFile(
    join(base, "update", "config.json"),
    JSON.stringify({ schemaVersion: 2, channel: "preview" }),
  );
  expect(await readChannel(base)).toBe("stable");
  await run(["channel", "preview"], "1.0.0");

  // The repository of the journey above: preview and stable offer 1.2.0. A
  // Machine that already runs something newer is never offered a downgrade,
  // whichever channel it switches to.
  const origins = [
    "--metadata-url",
    `${pages.url}metadata/`,
    "--target-url",
    `${pages.url}targets/`,
    "--loopback-fixture",
    "--check",
    "--json",
  ];
  const bootstrap = join(work, "bootstrap-root.json");
  await writeFile(bootstrap, await readFile(rootFile), { mode: 0o600 });
  const first = await run(
    [...origins, "--bootstrap-root", bootstrap],
    "1.3.0-rc.1",
  );
  expect(first.code).toBe(0);
  expect(JSON.parse(first.stdout)).toMatchObject({
    kind: "up-to-date",
    version: "1.3.0-rc.1",
    channelVersion: "1.2.0",
  });
  expect(await run(["channel", "stable"], "1.3.0-rc.1")).toMatchObject({
    code: 0,
  });
  const switched = await run(origins, "1.3.0-rc.1");
  expect(switched.code).toBe(0);
  expect(JSON.parse(switched.stdout).kind).toBe("up-to-date");
  // … and an older Machine on the configured channel is offered the update.
  expect((await run(origins, "1.0.0")).code).toBe(10);
});

test("a product built without release/root.json embeds no root and fails closed; built with one it needs no bootstrap root", async () => {
  const build = async (name: string, rootText: string | undefined) => {
    const output = join(work, name);
    const child = Bun.spawn(
      [
        process.execPath,
        "build",
        resolve(import.meta.dir, "../src/cli.ts"),
        "--compile",
        "--no-compile-autoload-dotenv",
        "--no-compile-autoload-bunfig",
        ...identityDefines({ version: "1.0.0", commit, target }),
        ...trustRootDefines(rootText),
        "--outfile",
        output,
      ],
      { stdout: "ignore", stderr: "pipe" },
    );
    if ((await child.exited) !== 0)
      throw new Error(await new Response(child.stderr).text());
    // Asynchronous: the repository is served by this very process.
    return async (args: string[]) => {
      const result = Bun.spawn([output, ...args], {
        env: { HOME: work },
        stdout: "pipe",
        stderr: "pipe",
      });
      const [stdout, stderr] = await Promise.all([
        new Response(result.stdout).text(),
        new Response(result.stderr).text(),
      ]);
      return {
        code: await result.exited,
        stdout: stdout.trim(),
        stderr: stderr.trim(),
      };
    };
  };
  const repository = [
    "--metadata-url",
    `${pages.url}metadata/`,
    "--target-url",
    `${pages.url}targets/`,
    "--loopback-fixture",
  ];
  const withoutRoot = await build("lazurio-without-root", undefined);
  const closed = join(work, "closed-base");
  // Against the compiled-in repository AND against a named one: no root, no
  // update. Nothing is fetched and no trust is written.
  for (const args of [[], repository])
    expect(
      await withoutRoot(["update", "--check", "--base", closed, ...args]),
    ).toEqual({
      code: 25,
      stdout: "",
      stderr: "Update failed: trust-missing",
    });
  expect(await readdir(join(closed, "trust"))).toEqual([]);
  // The root of the journey's repository is version 1; its chain leads to 2.
  const withRoot = await build(
    "lazurio-with-root",
    await readFile(rootFile, "utf8"),
  );
  const open = join(work, "open-base");
  for (let attempt = 0; attempt < 2; attempt++) {
    // The second run proves the compiled-in root is no `trust-conflict`.
    const checked = await withRoot([
      "update",
      "--check",
      "--json",
      "--base",
      open,
      ...repository,
    ]);
    expect(checked.code).toBe(10);
    expect(JSON.parse(checked.stdout)).toMatchObject({
      kind: "available",
      version: "1.2.0",
    });
  }
  expect(() => trustRootDefines('{"signed":{}}')).toThrow();
}, 120_000);
