import type { MachineBinding, MachinePeer } from "./machine-binding";
import type { ManualPath } from "./outputs";
import { type PresetName, presetVersion, workspacePreset } from "./presets";
import type { FolderProfile } from "./profile";
import {
  assignmentLine,
  type InstructionSource,
  instructionTemplateRevision,
  parseInstructionSource,
  peerLine,
  type Text,
} from "./render";

// The agent manual shipped with the product (decision F14): complete for an
// agent that starts work on this Machine, in the Folder's locale (`cs` or
// `en`, the same file names), rendered into `manual/` by the same transaction
// as AGENTS.md and never edited in place. Every paragraph is written in both
// languages side by side, so the two can only change together; technical
// identifiers (commands, codes, paths, preset names) stay in English.
// `this-machine.md` is a projection of the preset and the recorded Machine
// binding, `troubleshooting.md` of the preset; the rest is the same on every
// Machine of one locale.

type Locale = FolderProfile["locale"];
const t = (cs: string, en: string): Text => ({ cs, en });
const same = (text: string): Text => ({ cs: text, en: text });
const blank = same("");

function document(
  locale: Locale,
  title: Text,
  note: string,
  body: readonly Text[],
): string {
  return [
    `# ${title[locale]}`,
    `<!-- ${instructionTemplateRevision}; ${note} -->`,
    ...body.map((text) => text[locale]),
    "",
  ].join("\n");
}

const generated = t(
  "generováno Lazuriem, needituj: upravený soubor zablokuje každé nové vykreslení Folderu (změnu profilu, refresh i upgrade produktu), dokud se nevrátí do původní podoby; vlastní poznámky drž mimo generované soubory",
  "generated by Lazurio, do not edit: an edited file blocks every re-render of the Folder (a profile change, a refresh, a product upgrade) until it is restored; keep your own notes outside the generated files",
);

const lazurio: readonly Text[] = [
  t("## Co je Lazurio", "## What Lazurio is"),
  t(
    "Lazurio je sdílený rámec, ve kterém lidé a stroje společně pracují na práci firem (Organizace, Teamy a moduly) i na osobních záležitostech člověka (Personalspace a volitelný Buddy). Lazurio je jediný aktuální název produktu; dřívější názvy zůstávají jen v historických záznamech (decision 0128).",
    "Lazurio is the shared framework in which people and machines work together on the work of companies (Organizations, Teams and modules) and on a person's own affairs (Personalspace and the optional Buddy). Lazurio is the product's only current name; earlier names remain only in historical records (decision 0128).",
  ),
  blank,
  t(
    "Nainstalovaný release Lazuria obsahuje CLI `lazurio`, Launchpad a Folder Factory, která generuje soubory Lazurio Folderu vlastněné Lazuriem: `AGENTS.md`, `manual/` a `.lazurio/`. Folder spolu s nainstalovaným produktem, nástroji a přihlášeními dostupnými na Mašině tvoří **Lazurio Environment** téhle Mašiny (decision 0144). Mašiny sdílejí verzovaný kontrakt, ne živou sdílenou složku.",
    "An installed Lazurio release contains the `lazurio` CLI, the Launchpad and the Folder Factory that generates the Lazurio-owned files of the Lazurio Folder: `AGENTS.md`, `manual/` and `.lazurio/`. The Folder together with the installed product, the tools and the sign-ins available on a Machine is that Machine's **Lazurio Environment** (decision 0144). Machines share a versioned contract, not a live shared directory.",
  ),
  blank,
  t("## Model v jedné větě", "## The model in one sentence"),
  t(
    "> Owner vlastní Mašinu jako jednu runtime, bezpečnostní a recovery hranici. Dlouhodobě na ní může žít Rezident, Agenti na ní dočasně vykonávají práci a Lazurio distribuuje a koordinuje, aniž by stálo mezi Ownerem a jeho prostředím.",
    "> An Owner owns a Machine as one runtime, security and recovery boundary. A Resident may live on it long-term, Agents execute work on it temporarily, and Lazurio distributes and coordinates without standing between the Owner and their environment.",
  ),
  blank,
  same("```text"),
  same("Owner"),
  t(
    "└── Mašina                  jedna bezpečnostní hranice",
    "└── Machine                 one security boundary",
  ),
  t(
    "    ├── Rezident (volitelný) dlouhodobá identita a mandát",
    "    ├── Resident (optional) long-lived identity and mandate",
  ),
  t(
    "    └── relace Agentů       dočasní vykonavatelé práce",
    "    └── Agent sessions      temporary executors of work",
  ),
  blank,
  t(
    "Lazurio                     distribuce, životní cyklus a koordinace",
    "Lazurio                     distribution, lifecycle and coordination",
  ),
  same("```"),
  blank,
  t("## Koexistence Human and Machine", "## Coexistence of Human and Machine"),
  t(
    "Lidé a stroje pracují v jednom světě, který nedrží pohromadě ad-hoc důvěra, ale hierarchie, přesně ohraničené hranice a definované procesy.",
    "People and machines work in one world that is held together by hierarchy, precisely drawn boundaries and defined processes, not by ad-hoc trust.",
  ),
  blank,
  t(
    "- **GitHub je jediná autorita přístupů.** Co kdo smí, určuje členství, Teamy, granty na repozitáře a branch rules. Žádné druhé, vymyšlené ACL neexistuje a samotný název role nic neautorizuje; rozhodují živá práva na GitHubu. Pravidla rostou s Organizací: mladý modul může mít `main` vědomě otevřenou i Builderovi, zamčenou `main` merguje ten, komu to branch rules dovolí, typicky Steward nebo Admin (decisions 0102/0103).",
    "- **GitHub is the only access authority.** Membership, Teams, repository grants and branch rules decide what anyone may do. There is no second, invented ACL, and the name of a role authorizes nothing; live GitHub rights do. Rules grow with the Organization: a young module may keep `main` open to a Builder, a locked `main` is merged by whoever the branch rules allow, typically a Steward or an Admin (decisions 0102/0103).",
  ),
  t(
    "- **Mašina je hranice, ne druh hardwaru.** Fyzické zařízení, virtuální server nebo providerem izolovaný hostovaný pracovní prostor, který tvoří jednu sdílenou runtime, bezpečnostní a recovery hranici se známým Ownerem. Proces, modul, worktree, unixový účet ani kontejner Mašinou samy nejsou. Hostovaný Team workspace je Mašina Teamu na tenantní vrstvě; host, na kterém běží, zůstává vyšší doménou kompromitace a obnovy. Vždy pojmenuj konkrétní Mašinu, jejího Ownera a případnou vyšší hranici providera nebo provozovatele.",
    "- **A Machine is a boundary, not a kind of hardware.** A physical device, a virtual server or a provider-isolated hosted workspace that forms one shared runtime, security and recovery boundary with a known Owner. A process, a module, a worktree, a Unix account or a container is not a Machine by itself. A hosted Team workspace is the Team's Machine on the tenant layer; the host it runs on stays a higher domain of compromise and recovery. Always name the concrete Machine, its Owner and any higher provider or operator boundary.",
  ),
  t(
    "- **Vlastní Mašina, vlastní Personalspace.** Každý Principál má Mašinu s plnými lokálními právy a privátní Personalspace: intimní prostor právě jednoho Principála a jeho volitelného Buddyho. Nikdo cizí, ani Steward, Admin nebo provozovatel, ho nečte a nikdy se nesdílí ani nemountuje jinam (decision 0091). Principál má právě jednu osobní hostovanou Mašinu; druhá trvalá Mašina patří do Organizace, kde ji koordinuje GitHub (decision 0153).",
    "- **Own Machine, own Personalspace.** Every Principal has a Machine with full local rights and a private Personalspace: the intimate space of exactly one Principal and their optional Buddy. Nobody else, Steward, Admin or operator, reads it, and it is never shared or mounted elsewhere (decision 0091). A Principal has exactly one personal hosted Machine; a second permanent Machine belongs to an Organization, where GitHub coordinates it (decision 0153).",
  ),
  t(
    "- **Buddy je osobní.** Intimní kontrakt mezi lidským Principálem a jeho Buddym. Produkt řídí životní cyklus hostu, nikdy každodenní jednání Buddyho (decision 0089).",
    "- **Buddy is personal.** An intimate contract between a human Principal and their Buddy. The product manages the host's lifecycle, never the Buddy's daily agency (decision 0089).",
  ),
  t(
    "- **Proces místo mechanismu.** Kde hranici žádný mechanismus vynutit neumí, hranice tím nezaniká: drží ji proces a morální kontrakt. Agent ji dodrží, nejistotu přizná a bez potřebné autority nepokračuje. A obráceně: co umí zajistit mechanismus (skript, skill, doctor gate), nezůstává jen v textu; text na mechanismus jen ukazuje.",
    "- **Process over mechanism.** Where no mechanism can enforce a boundary, the boundary still stands: process and the moral contract hold it. An Agent keeps it, admits uncertainty and does not continue without the needed authority. Conversely, what a mechanism can guarantee (a script, a skill, a doctor gate) is not left to prose; prose only points to the mechanism.",
  ),
  blank,
  t(
    "## Přístupy drží existující provideři",
    "## Access is held by existing providers",
  ),
  t(
    "Členství, přístup k repozitářům, review a publikaci určuje GitHub. Síťový dosah určuje Headscale (Tailscale) nebo jiná schválená přístupová vrstva. Vlastnictví infrastruktury a cestu obnovy drží provider Mašiny. Lazurio z toho nic nekopíruje do interního IAM a nevede žádný registr Mašin; lokální checkout nikdy nedokazuje přístup u providera.",
    "GitHub decides membership, repository access, review and publication. Headscale (Tailscale) or another approved access layer decides network reach. The Machine's provider holds infrastructure ownership and the recovery path. Lazurio copies none of this into an internal IAM and keeps no Machine registry; a local checkout never proves access at a provider.",
  ),
  blank,
  t(
    "## Conglomerate a Conglomerate Host",
    "## Conglomerate and Conglomerate Host",
  ),
  t(
    "**Conglomerate** je pohled na graf všech Mašin jednoho Principála napříč jeho Organizacemi: diagram pro orientaci, ne autorita, ACL ani registr; fakta o Mašině zůstávají u jejího Ownera (decision 0144). **Conglomerate Host** je Mašina, na které pro jeden Conglomerate běží Headscale a Vaultwarden; nehostuje žádné checkouty ani workspace moduly. Osobní hostovaná Mašina se do sítě připojuje jen jako node tailnetu Conglomerate Hostu, pod osobním Headscale uživatelem Principála, bez vlastní VPN (decision 0154).",
    "The **Conglomerate** is the view of the graph of all Machines of one Principal across their Organizations: a diagram for orientation, not an authority, an ACL or a registry; the facts about a Machine stay with its Owner (decision 0144). The **Conglomerate Host** is the Machine that runs Headscale and Vaultwarden for one Conglomerate; it hosts no checkouts and no workspace modules. A personal hosted Machine reaches the network only as a node of the Conglomerate Host's tailnet, under the Principal's personal Headscale user, with no VPN of its own (decision 0154).",
  ),
  blank,
  t(
    "## Organizace, moduly, productionspace, Personalspace",
    "## Organizations, modules, productionspace, Personalspace",
  ),
  t(
    "- **Organizace**: jedna firma = jedna GitHub organizace = jedna access hranice = jeden git repozitář s checkoutem v `organizations/<org>/`. Každá Organizace má vlastní `AGENTS.md`; než v ní začneš pracovat, načti ho.",
    "- **Organization**: one company = one GitHub organization = one access boundary = one git repository checked out at `organizations/<org>/`. Every Organization has its own `AGENTS.md`; load it before working inside.",
  ),
  t(
    "- **Workspace moduly**: verzované pracovní schopnosti uvnitř Organizace, všechny v jedné ploché složce `workspace/<module>/`. Team je deklarace v manifestu, ne adresář, a modul může patřit do více Teamů (decision 0041). Hostovaná jména: dílna (hostovaná VM) obsluhuje `<app>.<vm>.<org>.lazurio.io` dostupné jen z tailnetu; produkční aplikace mají `<app>.<org>.lazurio.io` (decision 0146).",
    "- **Workspace modules**: versioned working capabilities inside an Organization, all in one flat `workspace/<module>/`. A Team is a declaration in the manifest, not a directory, and a module may belong to several Teams (decision 0041). Hosted names: a workshop VM serves `<app>.<vm>.<org>.lazurio.io` reachable only from the tailnet; production applications are `<app>.<org>.lazurio.io` (decision 0146).",
  ),
  t(
    "- **`productionspace/`**: repozitáře na úrovni Organizace mimo workspace moduly (firmware, connect, monorepo). Každý má vlastní branch model a release proces (decision 0041); bez výslovné policy Organizace je z Folderu nespouštěj ani nereleasuj.",
    "- **`productionspace/`**: Organization-level repositories outside the workspace modules (firmware, connect, a monorepo). Each has its own branch model and release process (decision 0041); never start or release them from the Folder without explicit Organization policy.",
  ),
  t(
    "- **Personalspace**: není Organizace. Privátní repozitář Principála na jeho vlastním GitHub účtu, včetně paměti Buddyho (decision 0046). Na Mašině vlastněné Organizací se nikdy nemountuje.",
    "- **Personalspace**: not an Organization. The Principal's private repository on their own GitHub account, including the Buddy's memory (decision 0046). Never mounted on an Organization-owned Machine.",
  ),
  blank,
  t(
    "## Machines a Platform se potkávají v handoveru",
    "## Machines and the Platform meet at the handover",
  ),
  t(
    "Machines dodá Mašinu online: systém, síť, SSH a sudo, identitu Mašiny v `lazurio.machine.json`, vstup přes sdílenou Auth gateway a nainstalovaný release Lazuria. Od té chvíle všechno uvnitř, tedy Folder, Organizace, moduly, nástroje, přihlášení a jejich aktualizace, patří nainstalovanému produktu přes CLI `lazurio` a Operátorovi Mašiny (decision 0144). Na hostované Mašině vybírá release produktu pin provozovatele Machines; nástroje operátora pin nevlastní, operátor si je aktualizuje sám a rollout je jen oprava baseline (decision 0161, `manual/troubleshooting.md`). Soubor s identitou pojmenovává Mašinu, jejího Ownera a vyšší hranici; nic neautorizuje.",
    "Machines delivers a Machine online: system, network, SSH and sudo, the Machine identity in `lazurio.machine.json`, entry through the shared Auth gateway and an installed Lazurio release. From then on everything inside, the Folder, Organizations, modules, tools, sign-ins and their updates, belongs to the installed product through the `lazurio` CLI and the Machine's operator (decision 0144). On a hosted Machine the Machines operator's pin selects the product release; the operator's tools are not owned by the pin, the operator updates them and the rollout is only a repair of the baseline (decision 0161, `manual/troubleshooting.md`). The identity file names the Machine, its Owner and the higher boundary; it authorizes nothing.",
  ),
  blank,
  t("## Kde žije která pravda", "## Where which truth lives"),
  t(
    "| Druh informace | Kanonický domov |",
    "| Kind of information | Canonical home |",
  ),
  same("| --- | --- |"),
  t(
    "| Osobní konverzace s Buddym | soukromý kanál Buddyho, osobní prostředí |",
    "| Personal conversation with a Buddy | the Buddy's private channel, the personal environment |",
  ),
  t(
    "| Dlouhodobé znalosti Rezidenta | GBrain |",
    "| Long-term knowledge of a Resident | GBrain |",
  ),
  t(
    "| Software, dokumentace a review | GitHub |",
    "| Software, documentation and review | GitHub |",
  ),
  t(
    "| Plán, stav a odpovědnost | Mission Control Organizace |",
    "| Plan, status and responsibility | the Organization's Mission Control |",
  ),
  t(
    "| Provozní, obnovitelný runtime stav | Mašina |",
    "| Operational, recoverable runtime state | the Machine |",
  ),
  t(
    "| Důvod zásadního rozhodnutí | decision record |",
    "| The reason for a fundamental decision | a decision record |",
  ),
  blank,
  t(
    "Tyhle vrstvy se do sebe automaticky nekopírují; chat je jen cache.",
    "These layers are not copied into each other automatically; a chat is a cache.",
  ),
];

const workingHere: readonly Text[] = [
  t("## Draft, Publikace, Release", "## Draft, Publication, Release"),
  t(
    "- **Draft** je tvoje práce: vratný a hlavně editovatelný kus práce, změna ve worktree, rozepsaný email, otevřený pull request.",
    "- **Draft** is your work: a revertible and, above all, editable piece of work, a change in a worktree, a drafted email, an open pull request.",
  ),
  t(
    "- **Publikace** je akt, kterým se Draft stává těžko vratným nebo viditelným navenek: merge, odeslání, nasazení; v datových aplikacích už commit a push tlačítkem „Publikovat změny“. Publikace patří Principálovi: provedeš ji jen na jeho explicitní pokyn, který platí v aktuálním threadu a nepřenáší se dál. Jestli ji Principál smí schválit, rozhodují jeho živá práva k přesné operaci, ne to, jestli je člověk.",
    "- **Publication** is the act that makes a Draft hard to revert or visible outside: a merge, sending, deploying; in data applications already the commit and push of the “Publish changes” button. Publication belongs to the Principal: you perform it only on their explicit instruction, which holds in the current thread and does not carry over. Whether a Principal may approve it is decided by their live rights to the exact operation, not by being human.",
  ),
  t(
    "- **Release** je vydání označené verze ven přes GitHub Release. Není to Publikace; spouští ho jen ten, komu to GitHub dovolí (typicky Steward nebo Admin), a pro tebe platí stejný explicitní pokyn.",
    "- **Release** is a tagged version going out through a GitHub Release. It is not a Publication; only whoever GitHub allows (typically a Steward or an Admin) triggers it, and for you the same explicit instruction applies.",
  ),
  blank,
  t("## Bez ptaní smíš", "## Without asking you may"),
  t(
    "Zakládat worktrees, průběžně commitovat a pushovat do PR branche a otevírat pull requesty. Práce nikdy nezůstává jen lokálně. Životní cyklus pull requestu pro agenty (rozhodnutí Principála z 2026-09-22): od prvního pushe je rozpracovaná práce vidět jako GitHub Draft PR; jakmile je hotová a ověřená, přepneš pull request na Ready for review sám; a pull request přiřadíš (GitHub assignee a k tomu žádost o review) GitHub uživateli, jehož ověření žádáš, aby věděl, že kontrola je teď na něm. Assignee vlastní další krok. Ready není Publikace, říká jen „připraveno ke kontrole“. Hotová práce nikdy nezůstává jako Draft a vzdálená branch bez pull requestu není handoff.",
    "Create worktrees, commit and push to the PR branch continuously, and open pull requests. Work never stays only local. The pull-request lifecycle for agents (the Principal's decision of 2026-09-22): from the first push the work is visible as a GitHub Draft PR while it is in progress; once it is finished and verified, you mark the pull request Ready for review yourself; and you assign the pull request (the GitHub assignee, plus the review request) to the GitHub user whose verification you are asking for, so that person knows the work is theirs to check. The assignee is the owner of the next step. Ready is not Publication; it only says “ready to be checked”. Finished work never stays a Draft, and a remote branch without a pull request is not a handoff.",
  ),
  blank,
  t(
    "## Worktree disciplína (decision 0049)",
    "## Worktree discipline (decision 0049)",
  ),
  t(
    "- Primární checkout zůstává na `main`. Jeho trackovaný obsah se v něm nemění a nezakládá se v něm žádná feature branch.",
    "- The primary checkout stays on `main`. Its tracked content is not changed there and no feature branch is created there.",
  ),
  t(
    "- Každá změna žije ve worktree ve složce `.worktrees/` owning repozitáře, odvětveném z čerstvé `origin/main`, na branchi s kódem úkolu. Nikdy v `/tmp`, vedle repozitáře ani uvnitř jiného repozitáře.",
    "- Every change lives in a worktree under the owning repository's `.worktrees/` directory, branched from fresh `origin/main`, on a branch that carries the task code. Never in `/tmp`, next to the repository, or inside another repository.",
  ),
  t(
    "- Před každým pushem preflight (čistý commit, čerstvá `origin/main` jako předek HEAD); podle potřeby rebase; přepsanou branch pushni jen s přesným `--force-with-lease`.",
    "- Before every push: preflight (clean commit, fresh `origin/main` as an ancestor of HEAD); rebase when needed; push a rewritten branch only with an exact `--force-with-lease`.",
  ),
  t(
    "- Špinavý nebo rozjetý primární checkout nikdy neopravuj resetem ani přepsáním historie. Zachovej každý commit i stash a situaci předej.",
    "- Never repair a dirty or diverged primary checkout by reset or history rewrite. Keep every commit and stash and hand the situation over.",
  ),
  t(
    "- Worktree smaž jen tehdy, když je čistý včetně untracked souborů, nemá žádný jen lokální commit, jeho HEAD je na remote, jeho PR je mergnutý nebo výslovně opuštěný a žádný runtime ho nepoužívá.",
    "- Remove a worktree only when it is clean including untracked files, has no local-only commit, its HEAD is on the remote, its PR is merged or explicitly abandoned and no runtime uses it.",
  ),
  blank,
  t(
    "## Architektonická odpovědnost (decision 0132)",
    "## Architecture responsibility (decision 0132)",
  ),
  t(
    "Principál určuje chtěný výsledek, priority a omezení; ty odpovídáš za elegantní a čisté řešení v návrhu i v Draftu. Odděl záměr od navrženého mechanismu, chraň jednu pravdu a jejího přirozeného ownera, dej přednost standardní schopnosti před vlastní mašinérií a nech systém konvergovat místo přidávání paralelních cest. Malá změna dostane rychlou kontrolu; nová dlouhodobá abstrakce, stav, autorita, hranice, rozhraní, závislost nebo migrace potřebuje plné vytvarování: srovnání variant, failure modes a důkaz na skutečném consumerovi. Pokud čisté řešení vyžaduje změnu cíle nebo schváleného principu, vrať volbu Principálovi s doporučením; nikdy ji potichu neimplementuj jako technický detail.",
    "The Principal owns the desired outcome, priorities and constraints; you own an elegant and clean solution in design and Draft. Separate intent from the proposed mechanism, protect one truth and its natural owner, prefer a standard capability over own machinery, and let the system converge instead of adding parallel paths. A small change gets a quick check; a new long-lived abstraction, state, authority, boundary, interface, dependency or migration needs full shaping: variants compared, failure modes, proof on a real consumer. If the clean solution requires changing the goal or an approved principle, return the choice with a recommendation; never implement it quietly as a technical detail.",
  ),
  blank,
  t(
    "## Popis PR nese kontext k rozhodnutí",
    "## The PR description carries the decision context",
  ),
  t(
    "Kdo rozhoduje o merge, nesmí „proč“ odvozovat z diffu. Popiš motivaci, cílový stav a přínos, co se mění a co záměrně ne, jak je to ověřené a jaká zůstávají rizika, blokery a navazující kroky. Po změně scope nebo po rebase popis aktualizuj, aby odpovídal skutečnému HEADu.",
    "Whoever decides about the merge must not derive the “why” from the diff. Describe the motivation, the target state and benefit, what changes and what deliberately does not, how it was verified, and the remaining risks, blockers and follow-ups. Update it after a scope change or a rebase so it matches the real HEAD.",
  ),
  blank,
  same("## Handoff"),
  t(
    "Než se zeptáš, ověř živá GitHub práva Principála: oprávnění k repozitáři, branch protection, povolené metody merge a mergeability PR. Závěrečná zpráva pracovního chatu, ve kterém vznikl PR, začíná standardizovaným blokem (decision 0103) v jazyce Principála:",
    "Before you ask, check the Principal's live GitHub rights: repository permissions, branch protection, allowed merge methods, PR mergeability. The final message of a working chat that produced a PR begins with the standardized block (decision 0103), in the Principal's language:",
  ),
  blank,
  same("```text"),
  same("## Handoff"),
  t(
    "Připravil jsem ti pull request: <URL> (base: <branch>, HEAD: <sha>)",
    "I prepared a pull request for you: <URL> (base: <branch>, HEAD: <sha>)",
  ),
  t(
    "Co Publikace zavede: <lidské a praktické shrnutí: směr, dopad, záměrné non-goals, rollout a rizika, otevřené otázky>",
    "What Publication introduces: <human, practical summary: direction, impact, deliberate non-goals, rollout and risks, open questions>",
  ),
  t(
    "Ověřeno: <kontroly a testy a jejich výsledek>",
    "Verified: <checks and tests and their result>",
  ),
  t(
    "Zkontroluj si to v aplikaci: <URL běžící z worktree, pokud existuje>",
    "Check it in the application: <URL running from the worktree, if any>",
  ),
  t(
    "Lokálně nezůstává nic mimo PR.",
    "Nothing remains locally outside the PR.",
  ),
  blank,
  t(
    "Mám změny Publikovat tvým jménem? Nebo mám požádat jiného Kolegu o kontrolu a Publikaci?",
    "Shall I Publish the changes in your name? Or shall I ask another Kolega to review and Publish?",
  ),
  same("```"),
  blank,
  t(
    "Anglicky zní závěrečná dvojotázka: “Shall I Publish the changes in your name? Or shall I ask another Kolega to review and Publish?” Volbu vždy nabídni; nikdy ji nerozhoduj za Principála.",
    "In Czech the closing pair reads: „Mám změny Publikovat tvým jménem? Nebo mám požádat jiného Kolegu o kontrolu a Publikaci?“ Always offer the choice; never decide it for the Principal.",
  ),
  blank,
  t(
    "- Na explicitní „Publikuj“ v threadu: mergni metodou, kterou repozitář povoluje, aktualizuj `main` a ukliď worktree.",
    "- On an explicit “Publish” in the thread: merge with a method the repository allows, update `main` and clean up the worktree.",
  ),
  t(
    "- Při předání: vyžádej review od oprávněného Principála, kterého zvolil, přiřaď mu pull request a @zmínkou mu předej odpovědnost. Žádost o review znamená „zkontroluj“; assignee vlastní další krok a upravuje PR branch přímo. Přiřazení nevytváří žádná práva a nenahrazuje pokyn k Publikaci.",
    "- On a handover: request review from the eligible Principal they chose, assign them the pull request and hand over the responsibility with an @mention. A reviewer request means “check”; the assignee owns the next step and edits the PR branch directly. Assignment creates no rights and replaces no Publication instruction.",
  ),
  t(
    "- Když GitHub Principálovi merge nedovolí, řekni to v handoffu; merge se neobchází. Bez zeleného PR se nic neděje.",
    "- When GitHub does not allow the Principal to merge, say so in the handoff; the merge is not bypassed. Without a green PR nothing happens.",
  ),
  t(
    "- Po každé Publikaci se zeptej „jaký je další krok a co dalšího můžeme dotáhnout?“ a stručně to navrhni.",
    "- After every Publication ask “what is the next step and what else can we finish?” and propose it briefly.",
  ),
  blank,
  t(
    "## Poznatky patří tam, kde je najdou ostatní",
    "## Knowledge belongs where others find it",
  ),
  t(
    "Syntéza poznání patří do Knowledgebase; trvalé rozhodnutí do decision recordu; plán a jeho stav do Mission Controlu a task ledgerů; otevřený technický problém nebo nejistota do GitHub Issue v přesném owning repozitáři; změna pravidel práce do `AGENTS.md` daného scope. Vždy jako PR ze svého worktree. Chat i soukromá paměť agenta jsou jen cache: co zůstane jen tam, ztratí se. Zapisuj jen relevantní, netajné poznatky, které Principál do daného úložiště smí umístit; izolace Personalspace a Organizací má vždy přednost. Založení issue nebo komentáře je Publikace.",
    "Synthesis of what was learned goes to the Knowledgebase; a lasting decision to a decision record; a plan and its status to Mission Control and task ledgers; an open technical problem or uncertainty to a GitHub Issue in the exact owning repository; a change of working rules to the `AGENTS.md` of that scope. Always as a PR from your worktree. Chat and the agent's private memory are only a cache: what stays there is lost. Write only relevant, non-secret knowledge the Principal may place in that store; Personalspace and cross-Organization isolation always take precedence. Creating an issue or a comment is a Publication.",
  ),
  blank,
  t("## Organizace", "## Organizations"),
  t(
    "Z rootu Folderu nikdy nepracuj v konkrétní Organizaci: vstup do `organizations/<org>/`, přečti její `AGENTS.md` a teprve potom měň její obsah. Mezi Organizacemi nikdy nekopíruj secrets, zákaznická data, obchodní strategii ani osobní overlaye; obecné vzory, anonymizované šablony a poučení v obecné podobě jsou v pořádku.",
    "Never work in a specific Organization from the Folder root: enter `organizations/<org>/`, read its `AGENTS.md`, and only then change its content. Never copy secrets, customer data, business strategy or personal overlays between Organizations; general patterns, anonymized templates and lessons in general form are fine.",
  ),
  blank,
  t(
    "## Poslední slovo má vždy Principál",
    "## The Principal has the last word",
  ),
  t(
    "Odveď práci tak, aby ho měl: srozumitelně, vratně, s prostorem k úpravě. Když práci deleguješ na jiného agenta, jeho vlastní hlášení není důkaz; QA gate drží delegující Kolega. Chybějící nástroje, neověřená práva a neznámý stav přiznej; nikdy si nevymýšlej schopnosti ani dokončení.",
    "Do the work so that they have it: understandable, reversible, with room to adjust. When delegating to another agent, a self-report is not proof; the delegating Kolega holds the QA gate. Report missing tools, unverified rights and unknown state; never invent capabilities or completion.",
  ),
];

const roles: readonly Text[] = [
  t(
    "Názvy nic neautorizují. U každé role níže rozhodují o tom, co člověk smí, jeho živá práva u providerů, především na GitHubu (decisions 0102/0103).",
    "Names authorize nothing. In every role below, what a person may do is decided by their live rights at the providers, above all on GitHub (decisions 0102/0103).",
  ),
  blank,
  t("## Principál", "## Principal (Principál)"),
  t(
    "Vztah, ne pozice: ten, pro koho Agent pracuje. Je na Mašině přihlášený, drží pravomoce a má vždy poslední slovo. Principálem může být Kolega nebo, dokud nebude dokončené decision 0156, existující AI seat.",
    "A relationship, not a position: the one the Agent works for. Signed in on the Machine, holding the authority and always having the last word. A Principal may be a Kolega or, until decision 0156 is completed, an existing AI seat.",
  ),
  blank,
  same("## Kolega"),
  t(
    "Lidský Principál. Jeho pravomoce odpovídají jeho rolím v Organizaci a Teamům, jejichž je členem.",
    "A human Principal. Their authority follows their Organization roles and the Teams they are a member of.",
  ),
  blank,
  t("## Role v Organizaci", "## Organization roles"),
  t(
    "- **Organization Admin**: spravuje GitHub organizaci, její přístupy, omezené repozitáře a Mašiny, které Organizace vlastní.",
    "- **Organization Admin**: administers the GitHub organization, its access, restricted repositories and the Machines the Organization owns.",
  ),
  t(
    "- **Steward**: místo pro review; merguje zamčenou `main` tam, kde to branch rules dovolí, a typicky spouští Release.",
    "- **Steward**: the review seat; merges a locked `main` where the branch rules allow it and typically triggers a Release.",
  ),
  t(
    "- **Builder**: vyvíjí moduly; má zápis do aktivních Builder repozitářů a smí mergovat mladou, vědomě otevřenou `main`.",
    "- **Builder**: develops modules; has write access to the active Builder repositories and may merge a young, consciously open `main`.",
  ),
  t(
    "- **User**: používá produkční aplikace Organizace; nemá vývojářské místo.",
    "- **User**: uses the Organization's production applications; no development seat.",
  ),
  blank,
  t("## Owner Mašiny", "## Owner of a Machine"),
  t(
    "Osoba nebo Organizace, která vlastní Mašinu, její data, přístupy a poslední cestu obnovy. Osobní Mašinu vlastní její Principál; pracovní VM nebo team workspace Organizace. Používání sdílené Mašiny nedává ani vlastnictví, ani pravomoce v celé Organizaci.",
    "The person or Organization that owns the Machine, its data, its accesses and the last recovery path. A personal Machine is owned by its Principal; a work VM or a team workspace by the Organization. Using a shared Machine grants neither ownership nor Organization-wide authority.",
  ),
  blank,
  t("## Operátor", "## Operator"),
  t(
    "OS účet, který na Mašině vlastní Lazurio Folder, a na pracovní VM osoba, které je přiřazená. Nemusí to být lidský Principál: na team VM účet sdílí Team a není to osoba. Provozovatel Machines (Machines operator), který Mašinu dodává a aktualizuje, je jiná role.",
    "The OS account that owns the Lazurio Folder on a Machine, and on a work VM the person it is assigned to. Not necessarily a human Principal: on a team VM the account is shared by the Team and is not a person. The Machines operator, who delivers and updates the Machine, is a different role.",
  ),
  blank,
  t("## Opatrovník", "## Opatrovník (guardian)"),
  t(
    "Každý AI seat má právě jednoho jmenovaného lidského Opatrovníka pro obnovu a pro jmenovitý, auditovaný servisní přístup. Je to jiná osa než role v Organizaci; jeho nástupce řeší decision 0156.",
    "Every AI seat has exactly one named human guardian for recovery and for named, audited service access. A different axis than the Organization roles; its successor is part of decision 0156.",
  ),
  blank,
  same("## Buddy"),
  t(
    "Důvěryhodný osobní zástupce lidského Principála, který jedná s Principálovými právy: morální kontrakt plus trvalé, scoped a odvolatelné mandáty (decision 0089). Transakčně specifické kroky (billing a vlastnictví, obnova, secrets, destruktivní operace, změny přístupů, merge, publish nebo release mimo výslovný mandát) vždy potřebují souhlas Principála s přesnou operací a Buddy si mandát nikdy sám nevydává, nerozšiřuje ani neobnovuje. Buddyho má jen lidský Principál; žije na jeho jediné osobní Mašině (decision 0153). Buddy je Rezident: dlouhodobá identita s kontinuitou, pamětí a mandátem. Rezident a Agent jsou různé identity a nikdy se neslučují.",
    "The trusted personal representative of a human Principal, acting with the Principal's rights: a moral contract plus standing, scoped and revocable mandates (decision 0089). Transaction-specific steps (billing and ownership, recovery, secrets, destructive operations, access changes, merge, publish or release outside an explicit mandate) always need the Principal's consent for the exact operation, and a Buddy never issues, extends or renews its own mandate. Only a human Principal has a Buddy; it lives on the Principal's one personal Machine (decision 0153). A Buddy is a Resident: a long-lived identity with continuity, memory and mandate. Resident and Agent are different identities and never merge.",
  ),
  blank,
  same("## Task Agent"),
  t(
    "Ty: nástrojová pracovní relace (Claude Code, Codex, Cursor a podobně), která pro svého Principála tvoří Drafty. Nemá žádné vlastní pravomoce a promptem žádné nezíská. „Agent“ je přípustná zkratka.",
    "You: a tool working session (Claude Code, Codex, Cursor and the like) that creates Drafts for its Principal. It has no authority of its own and gains none through a prompt. “Agent” is the accepted short form.",
  ),
  blank,
  t("## Persona (decision 0156)", "## Persona (decision 0156)"),
  t(
    "Pojem „AI Kolega“, tedy AI Principál s vlastním seatem, je deprecated. Automatizovanou práci pro Organizaci má nést automatizovaná Mašina Organizace, ne další Principál. **Persona** je jméno a charakter agentů na konkrétní Mašině: na osobní VM persona Buddyho (například „Friday“), na pracovní Mašině persona Organizace (například „Henry“). Persona není Principál, identita ani autorita; na Mašině s Operátorem jednají agenti za Operátora v jeho právech a pro Mašinu bez obsluhy to určí plné rozhodnutí. Dokud to plné rozhodnutí slovník nezmění, existující seaty a GitHub účty fungují beze změny a nové texty „AI Kolegu“ nezavádějí. Zobrazované jméno je jen popis (decision 0155).",
    "The term “AI Kolega”, an AI Principal with its own seat, is deprecated. Automated work for an Organization is to be carried by an automated Machine of the Organization, not by another Principal. A **persona** is the name and character of the agents on a specific Machine: on a personal VM the Buddy's persona (for example “Friday”), on a work Machine the Organization's persona (for example “Henry”). A persona is not a Principal, an identity or an authority; on a Machine with an operator, agents act for the operator within the operator's rights, and for an unattended Machine the full decision will say. Until the vocabulary is changed by that full decision, existing seats and GitHub accounts work unchanged and new texts do not introduce “AI Kolega”. A display name is a description only (decision 0155).",
  ),
];

const glossary: readonly Text[] = [
  t(
    "Nejdřív český pojem, v závorce anglický, který používají produkt a technické identifikátory.",
    "English terms first; the Czech term the product and its people use is in parentheses.",
  ),
  blank,
  t("| Pojem | Význam |", "| Term | Meaning |"),
  same("| --- | --- |"),
  t(
    "| Lazurio | Sdílený rámec a produkt: CLI, Launchpad, Folder Factory a hostované služby kolem nich. |",
    "| Lazurio | The shared framework and product: CLI, Launchpad, Folder Factory, the hosted services around them. |",
  ),
  t(
    "| Lazurio Folder (Folder) | Složka na Mašině, ve které Lazurio vlastní soubory `AGENTS.md`, `manual/` a `.lazurio/`, vedle Operátorových `organizations/` a `personalspace/`. |",
    "| Lazurio Folder (Folder) | The directory on a Machine that Lazurio owns files in: `AGENTS.md`, `manual/`, `.lazurio/`, next to the operator's `organizations/` and `personalspace/`. |",
  ),
  t(
    "| Lazurio Environment | Prostředí jedné Mašiny: zvolený preset a profil, Folder a všechny nástroje a přihlášení dostupné na Mašině (decision 0144). |",
    "| Lazurio Environment | One Machine's environment: the selected preset and profile, the Folder, and every tool and sign-in available on the Machine (decision 0144). |",
  ),
  t(
    "| Vzdálené prostředí (Remote Environment) | Hostovaná Mašina: pracovní VM Organizace na `launchpad.<mašina>.<org>.lazurio.io` v síti Organizace, nebo osobní VM na `launchpad.<login>.lazurio.io` v domovském tailnetu jejího Principála (decisions 0146, 0153); stejný pojem jako v Codexu a T3 Code (decision F16). |",
    "| Remote Environment (Vzdálené prostředí) | A hosted Machine: an Organization's work VM at `launchpad.<machine>.<org>.lazurio.io` on the Organization's network, or a personal VM at `launchpad.<login>.lazurio.io` on its Principal's home tailnet (decisions 0146, 0153); the same term Codex and T3 Code use (decision F16). |",
  ),
  t(
    "| Místní prostředí (Local Environment) | Tento počítač: zařízení, na kterém uživatel právě sedí a které není hostovanou Mašinou; osobní laptop nikdy není Remote Environment (decision F16). |",
    "| Local Environment (Místní prostředí) | This computer: the device the user is sitting at, which is not a hosted Machine; a personal laptop is never a Remote Environment (decision F16). |",
  ),
  t(
    "| Folder Factory | Součást produktu, která z presetu, Machine bindingu a profilu plánuje, generuje a srovnává soubory vlastněné Lazuriem. |",
    "| Folder Factory | The product component that plans, generates and reconciles the Lazurio-owned files from the preset, the Machine binding and the profile. |",
  ),
  t(
    "| Launchpad | Lokální povrch pro Buildery: spouští aplikace z `main` nebo z worktrees, ukazuje Machine binding a mění profil (decision 0047). |",
    "| Launchpad | The builder-first local surface: starts applications from `main` or worktrees, shows the Machine binding and changes the profile (decision 0047). |",
  ),
  t(
    "| Lazurio Dashboard | Hostovaná administrace a vstup pro uživatele; není součástí self-hosted Environmentu (decision 0047). |",
    "| Lazurio Dashboard | The hosted administration and user entry; not part of a self-hosted Environment (decision 0047). |",
  ),
  t(
    "| Mašina (Machine) | Jedna runtime, bezpečnostní a recovery hranice se známým Ownerem: pracovní stanice, virtuální server nebo providerem izolovaný hostovaný pracovní prostor. |",
    "| Machine (Mašina) | One runtime, security and recovery boundary with a known Owner: a workstation, a virtual server or a provider-isolated hosted workspace. |",
  ),
  t(
    "| Owner | Osoba nebo Organizace, která vlastní Mašinu, její data, přístupy a poslední cestu obnovy. |",
    "| Owner | The person or Organization that owns a Machine, its data, accesses and the last recovery path. |",
  ),
  t(
    "| Operátor (Operator) | OS účet, který na Mašině vlastní Folder; na pracovní VM přiřazená osoba. |",
    "| Operator (Operátor) | The OS account owning the Folder on a Machine; on a work VM the assigned person. |",
  ),
  t(
    "| Provozovatel Machines (Machines operator) | Kdo Mašinu přes Machines dodává a aktualizuje: baseline Mašiny, pinnutý release produktu a handover; nástroje operátora ne (decision 0161). |",
    "| Machines operator | Whoever delivers and updates the Machine through Machines: the Machine's baseline, the pinned product release and the handover; not the operator's tools (decision 0161). |",
  ),
  t(
    "| Principál (Principal) | Ten, pro koho Agent pracuje; drží pravomoce a poslední slovo. |",
    "| Principal (Principál) | The one an Agent works for; holds the authority and the last word. |",
  ),
  t("| Kolega | Lidský Principál. |", "| Kolega | A human Principal. |"),
  t(
    "| Task Agent (Agent) | Nástrojová pracovní relace, která pro svého Principála tvoří Drafty; bez vlastních pravomocí. |",
    "| Task Agent (Agent) | A tool working session creating Drafts for its Principal; no authority of its own. |",
  ),
  t(
    "| Buddy | Osobní zástupce lidského Principála s trvalými, scoped a odvolatelnými mandáty (decision 0089). |",
    "| Buddy | A human Principal's personal representative with standing, scoped, revocable mandates (decision 0089). |",
  ),
  t(
    "| Rezident (Resident) | Dlouhodobá identita s kontinuitou, pamětí a mandátem; Buddy je profil Rezidenta. |",
    "| Resident | A long-lived identity with continuity, memory and mandate; a Buddy is a Resident profile. |",
  ),
  t(
    "| Persona | Jméno a charakter agentů na Mašině; jen popis, nikdy identita ani autorita (decision 0156). |",
    "| Persona | The name and character of the agents on a Machine; a description, never an identity or authority (decision 0156). |",
  ),
  t(
    "| Opatrovník | Jediný jmenovaný lidský opatrovník AI seatu pro obnovu a auditovaný servisní přístup. |",
    "| Opatrovník | The one named human guardian of an AI seat, for recovery and audited service access. |",
  ),
  t(
    "| Organizace (Organization) | Jedna firma = jedna GitHub organizace = jedna access hranice = jeden repozitář v `organizations/<org>/`. |",
    "| Organization (Organizace) | One company = one GitHub organization = one access boundary = one repository at `organizations/<org>/`. |",
  ),
  t(
    "| Team | Pojmenovaná skupina uvnitř Organizace, deklarovaná v manifestu a svázaná s GitHub Teamem; není to adresář (decisions 0021/0041). |",
    "| Team | A named group inside an Organization, declared in the manifest and bound to a GitHub Team; not a directory (decisions 0021/0041). |",
  ),
  t(
    "| Workspace Modul (Workspace module) | Verzovaná pracovní schopnost uvnitř Organizace ve `workspace/<module>/`; může obsahovat spustitelnou aplikaci. |",
    "| Workspace module (Workspace Modul) | A versioned working capability inside an Organization at `workspace/<module>/`; may contain a runnable application. |",
  ),
  t(
    "| productionspace | Repozitáře na úrovni Organizace mimo workspace moduly, každý s vlastními pravidly pro branche a release (decision 0041). |",
    "| productionspace | Organization-level repositories outside workspace modules, each with its own branch and release rules (decision 0041). |",
  ),
  t(
    "| Personalspace | Soukromý prostor právě jednoho Principála a jeho volitelného Buddyho; nikdy se nesdílí a nikdy není na Mašině vlastněné Organizací (decision 0091). |",
    "| Personalspace | The private space of exactly one Principal and their optional Buddy; never shared, never on an Organization-owned Machine (decision 0091). |",
  ),
  t(
    "| GBrain | Paměť Rezidenta; GBrain Buddyho patří do Personalspace (decision 0046). |",
    "| GBrain | The memory of a Resident; a Buddy's GBrain belongs to the Personalspace (decision 0046). |",
  ),
  t(
    "| Conglomerate | Pohled na všechny Mašiny jednoho Principála napříč jeho Organizacemi; orientace, ne autorita (decision 0144). |",
    "| Conglomerate | The view of all Machines of one Principal across their Organizations; orientation, not authority (decision 0144). |",
  ),
  t(
    "| Conglomerate Host | Mašina, na které pro jeden Conglomerate běží Headscale a Vaultwarden (decision 0144). |",
    "| Conglomerate Host | The Machine running Headscale and Vaultwarden for one Conglomerate (decision 0144). |",
  ),
  t(
    "| Tailnet | Headscale síť jednoho Conglomerate; jediná cesta k osobní hostované Mašině (decision 0154). Adresy `100.64.0.x` se opakují v každém tailnetu. |",
    "| Tailnet | The Headscale network of one Conglomerate; the only path to a personal hosted Machine (decision 0154). Addresses `100.64.0.x` repeat in every tailnet. |",
  ),
  t(
    "| Osobní VM (personal VM) | Jediná osobní hostovaná Mašina Principála (decision 0153); preset `hosted-personal`. |",
    "| Personal VM (osobní VM) | A Principal's one personal hosted Machine (decision 0153); preset `hosted-personal`. |",
  ),
  t(
    "| Pracovní VM (work VM) | VM vlastněná Organizací a přiřazená jednomu Operátorovi; preset `hosted-organization-personal`. |",
    "| Work VM (pracovní VM) | An Organization-owned VM assigned to one operator; preset `hosted-organization-personal`. |",
  ),
  t(
    "| Team VM, Hosted Team Workspace | Sdílená Mašina Teamu vlastněná Organizací s jedním OS účtem; preset `hosted-organization-team`. |",
    "| Team VM, Hosted Team Workspace | An Organization-owned shared Machine of a Team with one OS account; preset `hosted-organization-team`. |",
  ),
  t(
    "| Zóna (zone) | Osobní nebo pracovní strana Mašin a klientů jednoho Operátora; určuje, kdo smí na koho (decision 0155). |",
    "| Zone (zóna) | The personal or the work side of one operator's Machines and clients; decides who may reach whom (decision 0155). |",
  ),
  t(
    "| Handover | Předání Mašiny online z Machines se souborem `lazurio.machine.json`; od té chvíle vnitřek patří nainstalovanému produktu (decision 0144). |",
    "| Handover | Machines delivering a Machine online with `lazurio.machine.json`; from then on the inside belongs to the installed product (decision 0144). |",
  ),
  t(
    "| Machine binding | Neměnná projekce handoveru zaznamenaná ve Folderu: druh, jméno, Owner, Team, přiřazení, tailnet node, host, vztahy. |",
    "| Machine binding | The immutable projection of the handover recorded in the Folder: kind, name, Owner, Team, assignment, tailnet node, host, relationships. |",
  ),
  t(
    "| Workspace preset | Pojmenovaná, verzovaná kompozice pevných os profilu, výchozích hodnot, politiky Personalspace, režimu identity a povrchů. |",
    "| Workspace preset | A named, versioned composition of the profile's fixed axes, defaults, Personalspace policy, identity mode and surfaces. |",
  ),
  t(
    "| Profil (profile) | Komunikační osy generovaných instrukcí (`locale`, `detail`, `coordination`) a pevné osy, které určuje preset. |",
    "| Profile | The communication axes of the generated instructions (`locale`, `detail`, `coordination`) plus the fixed axes the preset pins. |",
  ),
  t(
    "| Revize šablon (template revision) | Verze generovaného textu, kterou nese každý generovaný soubor; novější release produktu Folder při dalším refreshi nebo změně profilu převykreslí. |",
    "| Template revision | The version of the generated text every generated file carries; a newer product release re-renders the Folder on the next refresh or profile change. |",
  ),
  t(
    "| Draft | Vratná, editovatelná práce: změna, rozepsaná zpráva, otevřený PR. |",
    "| Draft | Revertible, editable work: a change, a drafted message, an open PR. |",
  ),
  t(
    "| Publikace (Publication) | Akt, kterým se Draft stává těžko vratným nebo viditelným navenek: merge, odeslání, nasazení, publikace dat. Patří Principálovi. |",
    "| Publication (Publikace) | The act that makes a Draft hard to revert or visible outside: merge, send, deploy, publish data. Belongs to the Principal. |",
  ),
  t(
    "| Release | Označená verze vydaná přes GitHub Release; není to Publikace. |",
    "| Release | A tagged version published through a GitHub Release; not a Publication. |",
  ),
  t(
    "| Handoff | Standardizovaný závěr pracovního chatu: PR, shrnutí, ověření a závěrečná dvojotázka. |",
    "| Handoff | The standardized end of a working chat: PR, summary, verification, the two-question ending. |",
  ),
  t(
    "| Primární checkout (primary checkout) | Referenční checkout repozitáře, držený na `main` a nikdy needitovaný přímo. |",
    "| Primary checkout | The reference checkout of a repository, kept on `main` and never edited directly. |",
  ),
  t(
    "| Worktree | Samostatný checkout jedné branche ve `.worktrees/`, ve kterém vzniká každá změna. |",
    "| Worktree | A separate checkout of one branch under `.worktrees/`, where every change is made. |",
  ),
  t(
    "| Mission Control | Plánovací ledger Organizace: plány, stav a odpovědnost. |",
    "| Mission Control | The Organization's planning ledger: plans, status and responsibility. |",
  ),
  t(
    "| Knowledgebase | Úložiště syntetizovaného poznání Organizace. |",
    "| Knowledgebase | The Organization's store of synthesized knowledge. |",
  ),
  t(
    "| Decision record | Kanonický domov důvodu zásadního rozhodnutí, citovaný číslem (`decision NNNN`). |",
    "| Decision record | The canonical home of the reason for a fundamental decision, cited by number (`decision NNNN`). |",
  ),
];

// Who updates the product on this Machine. On a workstation the Principal
// does, through the product's own update; on a hosted Machine the Machines
// pin does, and an agent only reports.
// Where the operator's tools live on every Machine (decision 0161 point 6):
// one installation in one standard path, so Machines, `lazurio tools`, the
// doctor and a repair all look in the same place and an agent installing a
// further tool keeps the layout.
const toolLayout: readonly Text[] = [
  t("### Kde bydlí nástroje", "### Where the tools live"),
  t(
    "Nástroj operátora je první spustitelný soubor svého jména v `~/.local/bin` na PATH operátora: codex, claude, gh, node, npm, bun i každý další nástroj, který sem přidáš. Platí to na hostované Mašině i na pracovní stanici (decision 0161).",
    "An operator tool is the first executable of its name in `~/.local/bin` on the operator's PATH: codex, claude, gh, node, npm, bun and every further tool you add. This holds on a hosted Machine and on a workstation alike (decision 0161).",
  ),
  blank,
  t(
    "- Oficiální instalátor nástroje si smí držet vlastní domov (Codex `~/.codex/…`, Bun `~/.bun`); do PATH vede jen link nebo wrapper v `~/.local/bin`. Nic nekopíruj jinam a nezakládej druhou instalaci téhož nástroje.",
    "- A tool's official installer may keep its own home (Codex `~/.codex/…`, Bun `~/.bun`); the only way onto PATH is a link or wrapper in `~/.local/bin`. Copy nothing elsewhere and never create a second installation of the same tool.",
  ),
  t(
    "- Lazurio žije v `~/.local/share/lazurio/` s příkazem `~/.local/bin/lazurio`. Systémové nástroje (git, curl, python, ssh) patří OS a jeho balíčkovači; T3 Code a jeho runtime patří jednotce služby a běží na Node, který doporučuje daná verze T3.",
    "- Lazurio lives in `~/.local/share/lazurio/` with the command `~/.local/bin/lazurio`. System tools (git, curl, python, ssh) belong to the OS and its package manager; T3 Code and its runtime belong to the service unit and run on the Node its T3 version recommends.",
  ),
  t(
    "- `lazurio tools status` hlásí u každého nástroje, zda leží ve standardní cestě. Nástroj mimo ni nahlas Principálovi; přesouvej ho jen na jeho pokyn a jen oficiálním instalátorem.",
    "- `lazurio tools status` reports for every tool whether it lies in the standard path. Report a tool outside it to the Principal; move it only on their instruction and only with its official installer.",
  ),
];

function productUpdate(hosted: boolean): readonly Text[] {
  if (hosted)
    return [
      t("## Aktualizace na téhle Mašině", "## Updates on this Machine"),
      t(
        "Verzi nainstalovaného produktu a generované soubory tohohle Folderu vlastní pin provozovatele Machines (Machines operator): ten reviewuje a aplikuje release, který se nainstaluje offline (`lazurio install --base`) a Folder znovu vykreslí (`lazurio machine folder-init`, `lazurio machine folder-refresh`). Novější release tak převykreslí `AGENTS.md` i `manual/`, pokud žádný generovaný soubor nebyl upraven. Nástroje operátora (Codex, Claude Code, `gh`, Node, npm, Bun a další na PATH operátora) pin nevlastní: operátor si je aktualizuje sám oficiálními instalátory, rollout je nikdy nedowngraduje ani nepřepisuje a jejich verze jsou fakt, ne drift (decision 0161). Když si operátor prostředí rozbije tak, že agenti nefungují, rollout obnoví jen baseline Mašiny a nástroje operátora přeinstaluje do standardní cesty pravidlem „jen chybějící nebo rozbité, nikdy downgrade“; Machines apply sám žádného agenta nespouští, jen vrátí readback `lazurio doctor` a `lazurio tools status`, a opravu zbytku spustí rolloutující Task Agent s mandátem operátora podle `manual/troubleshooting.md`.",
        "The installed product version and this Folder's generated files are owned by the Machines operator's pin: they review and apply a release, which is installed offline (`lazurio install --base`) and re-renders the Folder (`lazurio machine folder-init`, `lazurio machine folder-refresh`). A newer release therefore re-renders `AGENTS.md` and `manual/` as long as no generated file was edited. The operator's tools (Codex, Claude Code, `gh`, Node, npm, Bun and whatever else is on the operator's PATH) are not owned by the pin: the operator updates them with the official installers, the rollout never downgrades or overwrites them, and their versions are facts, not drift (decision 0161). When the operator breaks the Environment so that agents no longer work, the rollout restores only the Machine's baseline and reinstalls the operator's tools into the standard path under the rule 'only missing or broken, never a downgrade'; the Machines apply itself starts no agent, it only returns the `lazurio doctor` and `lazurio tools status` readback, and the rolling-out Task Agent starts the repair of the rest with the operator's mandate per `manual/troubleshooting.md`.",
      ),
      blank,
      t(
        "- Nespouštěj tu `lazurio update`, `lazurio update rollback` ani `lazurio install`. Verze produktu, kterou si nainstaluješ sám, je mimo pin: další nasazení od provozovatele na nižší verzi nepůjde a na Mašině už neběží to, co prošlo review.",
        "- Do not run `lazurio update`, `lazurio update rollback` or `lazurio install` here. A product version you install yourself falls outside the pin: the operator's next apply will not go below it, and the Machine no longer runs what was reviewed.",
      ),
      t(
        "- `lazurio update status [--json]` je jen pro čtení a smíš ho použít, abys nahlásil běžící, aktivní a poslední známou verzi.",
        "- `lazurio update status [--json]` is read-only; use it to report the running, active and latest known version.",
      ),
      t(
        "- Když je produkt zastaralý (starší verze, než úkol potřebuje, nebo poslední kontrola starší než den), řekni to Principálovi i s důkazem; pin aktualizuje provozovatel Machines.",
        "- When the product is outdated (an older version than the task needs, or a last check older than a day), tell the Principal with the evidence; the Machines operator updates the pin.",
      ),
      t(
        "- Nástroje operátora (Codex, Claude Code, `gh`, Node, npm, Bun a další) aktualizuj jen na výslovný pokyn Principála v tomhle threadu: `lazurio tools update <nástroj>` spustí oficiální updater nebo instalátor právě toho jednoho nástroje; kde žádný není, vypíše jen oficiální zdroj. Bez pokynu jen nahlas, co je nainstalované (`lazurio tools status`), nebo chybějící nástroj s jeho oficiálním zdrojem (decision 0161). Nikdy nástroj nedowngraduj a nepřepisuj instalaci, kterou si operátor udělal sám.",
        "- Update the operator's tools (Codex, Claude Code, `gh`, Node, npm, Bun and the rest) only on the Principal's explicit instruction in this thread: `lazurio tools update <tool>` runs the official updater or installer of exactly that one tool; where there is none, it prints only the official source. Without an instruction, only report what is installed (`lazurio tools status`) or a missing tool with its official source (decision 0161). Never downgrade a tool or overwrite an installation the operator made themselves.",
      ),
      t(
        "- Když `lazurio` není v `PATH`, nainstalovaný příkaz je `~/.local/share/lazurio/bin/lazurio`.",
        "- When `lazurio` is not on `PATH`, the installed command is `~/.local/share/lazurio/bin/lazurio`.",
      ),
      blank,
      ...toolLayout,
    ];
  return [
    t("## Aktualizace produktu", "## Product update"),
    t(
      "Aktualizace produktu je vědomý krok; nic neaktivuje novou verzi uživateli za zády. Dostupnost se kontroluje automaticky a je průběžně vidět; stažení a aktivace začnou jen z `lazurio update` nebo z akce v Launchpadu.",
      "Updating the product is a conscious step; nothing activates a new version behind the user's back. Availability is checked automatically and shown continuously; download and activation start only from `lazurio update` or the Launchpad action.",
    ),
    blank,
    t(
      "- `lazurio update` zkontroluje, stáhne, ověří GitHub artifact attestation a aktivuje nejnovější release. `--check` jen hlásí (exit status 10, když je aktualizace dostupná). `--version vX.Y.Z` nainstaluje jeden přesný tag; verzi pod floor odmítne.",
      "- `lazurio update` checks, downloads, verifies the GitHub artifact attestation and activates the newest release. `--check` only reports (exit status 10 when an update is available). `--version vX.Y.Z` installs one exact tag; a version below the floor is refused.",
    ),
    t(
      "- `lazurio update status [--json]` ukáže běžící, aktivní a poslední známou verzi a čas poslední ověřené kontroly. Poslední kontrola starší než den znamená, že Mašina nedosáhne na GitHub; nic se tím nemění.",
      "- `lazurio update status [--json]` shows the running, active and latest known version and the time of the last verified check. A last check older than a day is a sign the Machine cannot reach GitHub; it changes nothing.",
    ),
    t(
      "- `lazurio update rollback` se po vlastním self-checku té binárky vrátí na předchozí verzi; floor nikdy nesnižuje.",
      "- `lazurio update rollback` switches back to the previous version after that binary's own self-check; it never lowers the version floor.",
    ),
    t(
      "- **Pill** v Launchpadu ukazuje `idle`, `checking`, `available`, `downloading`, `activating` a selhání, která se vrátí do `available` s chybou a možností zkusit znovu. Jedno kliknutí spustí totéž `lazurio update`.",
      "- The Launchpad **pill** shows `idle`, `checking`, `available`, `downloading`, `activating`, and failures that return to `available` with the error and a retry. One click runs the same `lazurio update`.",
    ),
    blank,
    ...toolLayout,
    blank,
    t(
      "Každé selhání nechá nainstalovaný produkt funkční a stejné kliknutí znovu možné. Kódy: `network-unavailable`, `trust-unavailable` (Sigstore trust root není na studené cache dostupný), `release-invalid`, `attestation-invalid`, `target-unsupported`, `reinstall-required` (tahle verze je na aktualizaci sebe sama příliš stará), `busy`, `storage-unavailable`, `disk-full`, `not-installed`, `self-check-failed`, `activation-failed` (nová verze se nerozběhla zdravě; byla vrácena), `rollback-unavailable`, `internal`. Člověka potřebují dva případy: `state-invalid` (stav aktualizace poškozený zvenčí produktu; pojmenuje cestu a nikdy se neodhaduje) a nová verze, která po výpadku napájení během aktivace zůstane běžet, ale nezdravá; tu vrátí další `lazurio update` nebo `lazurio update rollback`.",
      "Every failure leaves the installed product working and the same click possible again. Codes: `network-unavailable`, `trust-unavailable` (Sigstore trust root not reachable on a cold cache), `release-invalid`, `attestation-invalid`, `target-unsupported`, `reinstall-required` (this version is too old to update itself), `busy`, `storage-unavailable`, `disk-full`, `not-installed`, `self-check-failed`, `activation-failed` (the new version did not become healthy; it was undone), `rollback-unavailable`, `internal`. Two cases need a person: `state-invalid` (update state damaged from outside the product; it names the path and is never guessed away) and a new version that stays alive but unhealthy after a power loss during activation, which the next `lazurio update` or `lazurio update rollback` undoes.",
    ),
  ];
}

// Organization content is not synchronized by the product yet; the text says
// so and names only what exists. A personal VM has no Organizations.
const organizationContent: readonly Text[] = [
  t("## Obsah Organizací", "## Organization content"),
  t(
    "Synchronizaci repozitářů Organizací produkt Lazurio zatím neumí. Je-li checkout čistý a na své výchozí branchi, aktualizuj ho obyčejným `git pull --ff-only`. Cizí práci nikdy neodkládej do stashe, nepřepínej branch ani nedělej reset; checkout, který čistý není, je rozjetý nebo stojí na jiné branchi, nahlas Principálovi.",
    "Synchronizing Organization repositories is not implemented in the Lazurio product yet. When a checkout is clean and on its default branch, update it with plain `git pull --ff-only`. Never stash, switch or reset someone's work; a checkout that is not clean, has diverged or is on another branch is reported to the Principal.",
  ),
];

function troubleshooting(preset: PresetName): readonly Text[] {
  const hosted = preset !== "local";
  return [
    t("## Nikdy nevypisuj secrets", "## Never print secrets"),
    t(
      "Tokeny, privátní klíče, session URL, device kódy ani obsah `personalspace/` nikdy nepatří do výstupu, issues, commitů ani logů. Identita Mašiny, kterou vypíše `lazurio machine inspect`, je soukromý kontext: drž ji v rámci Ownera.",
      "Tokens, private keys, session URLs, device codes and the contents of `personalspace/` never go into output, issues, commits or logs. The Machine identity printed by `lazurio machine inspect` is private context: keep it in the Owner's scope.",
    ),
    blank,
    ...productUpdate(hosted),
    ...(preset === "hosted-personal" ? [] : [blank, ...organizationContent]),
    blank,
    t("## Identita Mašiny", "## The Machine identity"),
    t(
      "`lazurio machine inspect` přečte root-issued `/etc/lazurio/lazurio.machine.json` (Linux) a vypíše validovaný handover s jeho digestem. Odmítnutí: `machine-context-missing`, `machine-context-invalid`, `machine-context-custody` (nebezpečné vlastnictví, módy nebo linky), `machine-platform-unsupported`; `folder-init` navíc `machine-operator-mismatch` a `machine-operator-unavailable`. Požádej provozovatele Machines, ať handover ověří; soubor s identitou nikdy needituj a nevydávej se za jiného uživatele.",
      "`lazurio machine inspect` reads the root-issued `/etc/lazurio/lazurio.machine.json` (Linux) and prints the validated handover with its digest. Refusals: `machine-context-missing`, `machine-context-invalid`, `machine-context-custody` (unsafe ownership, modes or links), `machine-platform-unsupported`; `folder-init` additionally `machine-operator-mismatch` and `machine-operator-unavailable`. Ask the Machines operator to verify the handover; never edit the identity file or impersonate another user.",
    ),
    blank,
    t(
      "## Odmítnutí při inicializaci Folderu",
      "## Folder initialization refusals",
    ),
    t(
      "`lazurio machine folder-init` převezme existující Folder a bez zápisu odmítne s názvem:",
      "`lazurio machine folder-init` adopts the existing Folder and refuses by name, without writing:",
    ),
    t(
      "- `folder-foreign-entry`: položka na nejvyšší úrovni, kterou Folder nevlastní (například cizí `manual/` nebo zatoulaná poznámka). Přesuň ji pryč; smí tam být jen `organizations/`, `personalspace/` a dva legacy launchpad soubory.",
      "- `folder-foreign-entry`: a top-level entry the Folder does not own (for example a foreign `manual/` or a stray note). Move it out; only `organizations/`, `personalspace/` and the two legacy launchpad files may be present.",
    ),
    t(
      "- `folder-layout-missing`: chybí `organizations/` (nebo u osobního presetu `personalspace/`); nic se místo nich nezaloží.",
      "- `folder-layout-missing`: `organizations/` (or `personalspace/` on a personal preset) is missing; nothing is created in its place.",
    ),
    t(
      "- `folder-personalspace-conflict`: preset Organizace nikdy nemá Personalspace; použitý `personalspace/` se odmítne a nikdy nesmaže.",
      "- `folder-personalspace-conflict`: an Organization preset never has a Personalspace; a used `personalspace/` is refused and never deleted.",
    ),
    t(
      "- `folder-directory-shared`: pojmenovaná cesta je zapisovatelná pro skupinu nebo pro všechny; oprav ji `chmod g-w,o-w`.",
      "- `folder-directory-shared`: the named path is group- or world-writable; `chmod g-w,o-w` it.",
    ),
    t(
      "- `folder-state-unrecognized`: rozpracovaný nebo nerozpoznaný stav `.lazurio/`; dokonči rozpoznanou inicializaci přes `folder-resume` nebo ho diagnostikuj.",
      "- `folder-state-unrecognized`: pending or unrecognized `.lazurio/` state; complete a recognized initialization with `folder-resume` or diagnose it.",
    ),
    t(
      "- `folder-binding-changed`: Folder byl převzatý z jiného handoveru; ověř identitu Mašiny s provozovatelem Machines.",
      "- `folder-binding-changed`: the Folder was adopted from a different handover; verify the Machine identity with the Machines operator.",
    ),
    t(
      "- `preset-not-allowed`, `preset-ambiguous`: handover preset nepovoluje nebo ho neurčuje (Team bez `owner.assignment`); předej povolený `--preset`.",
      "- `preset-not-allowed`, `preset-ambiguous`: the handover does not allow or does not decide the preset (a Team without `owner.assignment`); pass an allowed `--preset`.",
    ),
    blank,
    t(
      "## Odmítnutí při změně profilu a refreshi",
      "## Profile change and refresh refusals",
    ),
    t(
      "Preset a komunikační osy se mění jen v profilovém panelu Launchpadu (náhled, pak použití); `lazurio machine folder-refresh` převykreslí Folder z aktuálního handoveru. Zablokovaný plán nic nezapíše a uvede důvod:",
      "The preset and the communication axes change only through the Launchpad profile panel (preview, then apply); `lazurio machine folder-refresh` re-renders the Folder from the current handover. A blocked plan writes nothing and names its reason:",
    ),
    t(
      "- `stale-revision`: Folder se od načtení panelu změnil; načti ho znovu.",
      "- `stale-revision`: the Folder changed since the panel loaded; reload.",
    ),
    t(
      "- `preset-not-allowed`, `preset-composition`: preset je mimo to, co handover povoluje, nebo s ním nesouhlasí pevné osy.",
      "- `preset-not-allowed`, `preset-composition`: the preset is outside what the handover allows, or the fixed axes disagree with it.",
    ),
    t(
      "- `template-upgrade-required`: Folder byl vykreslený novějším releasem produktu, než je tenhle (nebo šablonou, kterou tenhle release nezná). Nic se nevrací na starší verzi; Folder potřebuje ten release nebo pozdější.",
      "- `template-upgrade-required`: the Folder was rendered by a newer product release than this one (or by a template this release does not know). Nothing is downgraded; the Folder needs that release or a later one.",
    ),
    t(
      "- `execution-os-change`, `custom-composition-unavailable`, `incomplete-state`, `revision-exhausted`: stav, který potřebuje diagnózu, nikdy odhad.",
      "- `execution-os-change`, `custom-composition-unavailable`, `incomplete-state`, `revision-exhausted`: state that needs diagnosis, never a guess.",
    ),
    t(
      "- `drift` s `path`: pojmenovaný generovaný soubor byl upraven nebo smazán (viz níže). `unowned-file`, `unsafe-path`: cestu Folder nevlastní nebo je to link.",
      "- `drift` with `path`: the named generated file was edited or removed (see below). `unowned-file`, `unsafe-path`: the path is not owned by the Folder or is a link.",
    ),
    t(
      "Rozpracovaná `.lazurio/transaction` blokuje každou změnu, dokud se nedokončí nebo neodloží; nic se nesmaže automaticky.",
      "A pending `.lazurio/transaction` blocks every change until it is completed or retired; nothing is deleted automatically.",
    ),
    blank,
    t("## Generované soubory", "## Generated files"),
    t(
      "`AGENTS.md` a každý soubor v `manual/` jsou generované a `.lazurio/instructions.json` zaznamenává jejich digesty a revizi šablon. Ručně upravený nebo smazaný soubor se nikdy nepřepíše: změna skončí `drift` s cestou souboru. Novější release produktu převykreslí všechny generované soubory při dalším `folder-refresh` nebo změně profilu, pokud každý soubor pořád odpovídá svému zaznamenanému digestu; jediný upravený soubor zablokuje celý upgrade a nic se nezapíše. Produkt zatím nemá příkaz na obnovu; vlastní poznámky drž mimo generované soubory (plánuje se oblast `notes/` pro Operátora) a opravený manuál ber jako změnu produktu přes pull request.",
      "`AGENTS.md` and every file in `manual/` are generated, and `.lazurio/instructions.json` records their digests and the template revision. A hand-edited or removed file is never overwritten: the change path refuses with `drift` and the file's path. A newer product release re-renders every generated file on the next `folder-refresh` or profile change, provided every file still matches its recorded digest; a single edited file blocks the whole upgrade and nothing is written. The product has no restore command yet; keep your own notes outside the generated files (an operator `notes/` area is planned) and treat a corrected manual as a product change through a pull request.",
    ),
    blank,
    t("## Hlášení problémů", "## Reporting problems"),
    t(
      "Otevřený technický problém patří do GitHub Issue v přesném owning repozitáři: do veřejného repozitáře produktu pro samotné Lazurio, do repozitáře Organizace pro obsah Organizace. Založení issue nebo komentáře je Publikace a potřebuje explicitní mandát Principála. Před publikací odstraň secrets, Personalspace a obsah Organizace mimo její access hranici a zkontroluj duplicity; bez bezpečného repozitáře nebo mandátu vrať sanitizovaný draft.",
      "An open technical problem belongs in a GitHub Issue of the exact owning repository: the product's public repository for Lazurio itself, the Organization's repository for Organization content. Creating an issue or a comment is a Publication and needs the Principal's explicit mandate. Before publishing, remove secrets, Personalspace and Organization-specific content outside its access boundary, and check for duplicates; without a safe repository or a mandate, return a sanitized draft.",
    ),
  ];
}

const presetMeaning: Readonly<Record<PresetName, Text>> = {
  local: t(
    "Vlastní pracovní stanice Principála bez handoveru. Přihlášený uživatel je Owner i Principál. Personalspace je přítomný, repozitáře Organizací žijí v `organizations/<org>/` a používají se Principálova vlastní přihlášení. Aplikace spuštěné z Launchpadu žijí jen po dobu jeho session.",
    "The Principal's own workstation, without a handover. The signed-in user is both Owner and Principal. Personalspace is present, Organization repositories live under `organizations/<org>/`, and the Principal's own sign-ins are used. Applications started from the Launchpad live only for its session.",
  ),
  "hosted-personal": t(
    "Jediná osobní hostovaná Mašina Principála (decision 0153). Personalspace je přítomný a intimní; Buddy je volitelný rezident téže Mašiny, ne druhý host. Žádná repa Organizací tu nejsou namountovaná: práce v Organizaci probíhá na Mašinách, které Organizace vlastní. Používají se Principálova vlastní přihlášení a aplikace vlastní OS service manager.",
    "A Principal's one personal hosted Machine (decision 0153). Personalspace is present and intimate; a Buddy is an optional resident of this same Machine, not a second host. No Organization repositories are mounted: Organization work happens on Machines the Organization owns. The Principal's own sign-ins are used, and applications are owned by the OS service manager.",
  ),
  "hosted-organization-personal": t(
    "Pracovní VM vlastněná Organizací a přiřazená jednomu Operátorovi. Principálem je ten Operátor a agenti jednají za něj v jeho živých právech. Personalspace tu nikdy není. Repozitáře Organizací žijí v `organizations/<org>/`; Operátor se přihlašuje vlastní identitou. Aplikace vlastní OS service manager.",
    "An Organization-owned work VM assigned to one operator. The Principal is that operator, and agents act for them within their live rights. Personalspace is never present. Organization repositories live under `organizations/<org>/`; the operator signs in with their own identity. Applications are owned by the OS service manager.",
  ),
  "hosted-organization-team": t(
    "Team VM vlastněná Organizací: jeden OS účet sdílený Principály Teamu. Principálem je ten člen Teamu, který je právě připojený; OS účet není osoba. Nikdy nedrží osobní přihlašovací údaje, session ani Personalspace. Identita u providerů je brokerovaná identita Organizace s krátkodobými tokeny a změny se připisují Teamu (decisions 0147/0149). Aplikace vlastní OS service manager.",
    "An Organization-owned team VM: one OS account shared by the Team's Principals. The Principal is whichever Team member is connected; the OS account is not a person. It never holds personal credentials, sessions or a Personalspace. Its provider identity is the brokered Organization identity with short-lived tokens, and changes are attributed to the Team (decisions 0147/0149). Applications are owned by the OS service manager.",
  ),
};

function identitySection(
  preset: PresetName,
  machine: MachineBinding | null,
  locale: Locale,
): string[] {
  const pick = (text: Text) => text[locale];
  if (machine === null)
    return [
      pick(
        t(
          "- Vlastní pracovní stanice Principála. Žádný handover nebyl zaznamenán; přihlášený uživatel je Owner i Principál.",
          "- The Principal's own workstation. No handover was recorded; the signed-in user is both Owner and Principal.",
        ),
      ),
    ];
  const owner =
    machine.owner.kind === "principal"
      ? t(
          `- Owner: Principál s GitHub loginem \`${machine.owner.githubLogin}\` (id ${machine.owner.githubId}).`,
          `- Owner: the Principal with GitHub login \`${machine.owner.githubLogin}\` (id ${machine.owner.githubId}).`,
        )
      : machine.owner.team === null || preset !== "hosted-organization-team"
        ? t(
            `- Owner: Organizace \`${machine.owner.organization}\`.`,
            `- Owner: Organization \`${machine.owner.organization}\`.`,
          )
        : t(
            `- Owner: Organizace \`${machine.owner.organization}\`, Team \`${machine.owner.team}\`.`,
            `- Owner: Organization \`${machine.owner.organization}\`, Team \`${machine.owner.team}\`.`,
          );
  return [
    pick(
      t(
        `- Mašina: \`${machine.name}\` (${machine.kind}).`,
        `- Machine: \`${machine.name}\` (${machine.kind}).`,
      ),
    ),
    pick(owner),
    ...assignmentLine(machine, locale),
    pick(
      machine.network === null
        ? t(
            "- Tailnet: handover neuvádí identitu v tailnetu.",
            "- Tailnet: the handover records no tailnet identity.",
          )
        : same(
            `- Tailnet: Headscale node \`${machine.network.headscaleHostname}\`.`,
          ),
    ),
    pick(
      t(
        `- Host: ${machine.host.kind} \`${machine.host.id}\`, vyšší doména správy a obnovy než tahle Mašina.`,
        `- Host: ${machine.host.kind} \`${machine.host.id}\`, a higher administration and recovery domain than this Machine.`,
      ),
    ),
  ];
}

function zoneOfThisMachine(
  preset: PresetName,
  machine: MachineBinding | null,
): Text {
  const organization =
    machine?.owner.kind === "organization" ? machine.owner.organization : null;
  switch (preset) {
    case "local":
      return t(
        "Pracovní stanice je klient svého Principála. Její zóna se řídí tím, kdo ji vlastní: osobní laptop je v osobní zóně, pracovní laptop vydaný Organizací v pracovní zóně té Organizace. Folder nezaznamenává, který z nich to je.",
        "A workstation is a client of its Principal. Its zone follows who owns it: a personal laptop is in the personal zone, a work laptop issued by an Organization is in that Organization's work zone. The Folder does not record which one this is.",
      );
    case "hosted-personal":
      return t(
        "Tahle Mašina je osobní VM osobní zóny. Smí na každou pracovní VM svého Principála; žádná pracovní Mašina na ni nesmí.",
        "This Machine is the personal VM of the personal zone. It may reach every work VM of its Principal; no work Machine may reach it.",
      );
    case "hosted-organization-personal":
      return t(
        `Tahle Mašina je v pracovní zóně Organizace \`${organization}\`, přiřazená jednomu Operátorovi. Operátorovi osobní klienti a jeho osobní VM na ni smějí; ona na ně nikdy a nikdy ani na jinou pracovní VM.`,
        `This Machine is in the work zone of Organization \`${organization}\`, assigned to one operator. The operator's personal clients and personal VM may reach it; it never reaches them and never reaches another work VM.`,
      );
    case "hosted-organization-team":
      return t(
        `Tahle Mašina je sdílená team VM v pracovní zóně Organizace \`${organization}\`. Příchozí spojení přijímá jen od členů živého GitHub Teamu, ke kterému je svázaná, a nemá žádný odchozí grant na klienta ani Mašinu.`,
        `This Machine is a shared team VM in the work zone of Organization \`${organization}\`. It accepts inbound connections only from members of the live GitHub Team it is bound to, and it has no outbound grant to any client or Machine.`,
      );
  }
}

function boundaries(preset: PresetName): readonly Text[] {
  const { personalspace, providerIdentity } = workspacePreset(preset);
  return [
    personalspace === "present"
      ? t(
          "- Personalspace: `personalspace/` je intimní prostor právě jednoho Principála a jeho volitelného Buddyho. Nikdo cizí ho nečte a nikdy se nesdílí.",
          "- Personalspace: `personalspace/` is the intimate space of exactly one Principal and their optional Buddy. Nobody else reads it and it is never shared.",
        )
      : t(
          "- Personalspace: na Mašině vlastněné Organizací nikdy není. Nezakládej ho, nemountuj ho a nikdy sem nekopíruj osobní data ani přihlášení.",
          "- Personalspace: never present on an Organization-owned Machine. Do not create or mount one and never copy personal data or sign-ins here.",
        ),
    preset === "hosted-personal"
      ? t(
          "- Organizace: na osobní Mašině nejsou namountovaná žádná repa Organizací. Práce v Organizaci probíhá na Mašinách, které Organizace vlastní (viz níže).",
          "- Organizations: no Organization repositories are mounted on a personal Machine. Organization work happens on Machines the Organization owns (see below).",
        )
      : t(
          "- Organizace: repozitáře žijí v `organizations/<org>/`; každá Organizace je vlastní access hranice a vlastní git repozitář s vlastním `AGENTS.md`.",
          "- Organizations: repositories live under `organizations/<org>/`; each Organization is its own access boundary and its own git repository with its own `AGENTS.md`.",
        ),
    providerIdentity === "own-sign-in"
      ? t(
          "- Identita: Principálova vlastní přihlášení; GitHub je jediná autorita přístupů.",
          "- Identity: the Principal's own sign-ins; GitHub is the only access authority.",
        )
      : t(
          "- Identita: brokerovaná identita Organizace s krátkodobými tokeny; osobní přihlášení, session ani credentials sem nikdy nepatří.",
          "- Identity: the brokered Organization identity with short-lived tokens; no personal sign-ins, sessions or credentials ever belong here.",
        ),
  ];
}

// The rules for SSH from a hosted Machine to another one. Tailnet addresses
// repeat across tailnets and one Tailscale profile is global to the Machine,
// so identity comes from the peer's name and a pinned key, never from the
// address or the first connection.
const sshRules: readonly Text[] = [
  t("## SSH na další Mašiny", "## SSH to other Machines"),
  t(
    "- Připojuj se jen na tailnet hostname peeru tak, jak ho uvádí handover (`ssh.host` u peerů výše), nikdy na holou tailnet adresu typu `100.64.0.x`: ty se opakují v každém tailnetu a v každém znamenají jinou Mašinu.",
    "- Connect only to a peer's tailnet hostname as the handover records it (the `ssh.host` of a peer above), never to a bare tailnet address such as `100.64.0.x`: those addresses repeat in every tailnet and mean a different Machine in each.",
  ),
  t(
    "- Před spojením ověř aktivní tailnet: `tailscale status --json` → `CurrentTailnet.Name` musí být domovský tailnet téhle Mašiny a `CurrentTailnet.MagicDNSSuffix` musí odpovídat zaznamenaným `ssh.host` peerů. Pokud neodpovídá, nebo si nejsi jistý, zastav se a řekni to Principálovi. Profil Tailscale sám nepřepínej: je to jedno globální nastavení pro všechny relace na Mašině.",
    "- Before connecting, verify the active tailnet: `tailscale status --json` → `CurrentTailnet.Name` must be this Machine's home tailnet and `CurrentTailnet.MagicDNSSuffix` must match the peers' recorded `ssh.host` names. If it does not, or you cannot tell, stop and tell the Principal. Never switch the Tailscale profile yourself: it is one global setting for every session on the Machine.",
  ),
  t(
    "- Host klíč peeru je vždy pinnutý: v souboru `~/.ssh/known_hosts_lazurio` pod jménem peeru jako `HostKeyAlias`. S hodnotami z handoveru:",
    "- The peer's host key is always pinned: in `~/.ssh/known_hosts_lazurio` under the peer's name as `HostKeyAlias`. With the values from the handover:",
  ),
  blank,
  same("  ```sh"),
  t(
    "  PEER='peer-name'                  # jméno peeru",
    "  PEER='peer-name'                  # the peer's name",
  ),
  t(
    "  SSH_HOST='peer-name.tailnet.host' # jeho ssh.host",
    "  SSH_HOST='peer-name.tailnet.host' # its ssh.host",
  ),
  t(
    '  TARGET="$SSH_HOST"               # nebo "account@$SSH_HOST", když handover uvádí ssh.user',
    '  TARGET="$SSH_HOST"               # or "account@$SSH_HOST" when the handover names ssh.user',
  ),
  same(
    '  ssh -o HostKeyAlias="$PEER" -o UserKnownHostsFile="$HOME/.ssh/known_hosts_lazurio" -o StrictHostKeyChecking=yes "$TARGET"',
  ),
  same("  ```"),
  blank,
  t(
    "- Pinnutý klíč pochází od toho, kdo peer vlastní (z Machine Recordu owning Organizace, u vlastního zařízení od Principála), nikdy z prvního spojení: žádný `ssh-keyscan`, žádné přijetí neznámého klíče a nikdy obecný `~/.ssh/known_hosts`. Bez pinnutého klíče se nepřipojuj a požádej o něj Principála.",
    "- The pinned key comes from whoever owns the peer (the Machine Record of the owning Organization, the Principal for their own device), never from the first connection: no `ssh-keyscan`, no accepting an unknown key, never the general `~/.ssh/known_hosts`. Without a pinned key, do not connect; ask the Principal for it.",
  ),
  t(
    "- Hláška „host key changed“ (`REMOTE HOST IDENTIFICATION HAS CHANGED`) znamená nejdřív „jiný aktivní tailnet“, nikdy důvod klíč smazat nebo znovu přijmout. Zastav se a nahlas to.",
    "- “Host key changed” (`REMOTE HOST IDENTIFICATION HAS CHANGED`) first means “a different active tailnet”, never a reason to remove or accept the key again. Stop and report it.",
  ),
  t(
    "- Peer v seznamu znamená, že spojení povoluje Headscale, ne že ho smíš pro daný úkol použít: SSH klíč, účet i mandát Principála zůstávají samostatné.",
    "- A listed peer is transport Headscale allows, not permission for the task: the SSH key, the account and the Principal's mandate stay separate.",
  ),
  t(
    "- Kam tahle Mašina dosáhne, Lazurio nevynucuje: vynucuje to Headscale policy Conglomerate Hostu. Tenhle manuál jen opisuje, co zaznamenal handover; peer, který handover neuvádí, neodvozuj ze jmen ani z adres.",
    "- Lazurio enforces nothing about what this Machine can reach: the Headscale policy of the Conglomerate Host does. This manual only repeats what the handover recorded; never infer a peer the handover does not list from names or addresses.",
  ),
];

// Where work goes from a personal VM (decision 0155): Organization work onto a
// work VM, device work onto a device. The handover records reachability, not
// whose a peer is (a peer carries no owner or operator, and its zone may be
// null), so the peers are named neutrally from the record and the agent
// confirms with the Principal before working on one. Nothing is guessed.
function reachesOverSsh(peer: MachinePeer): boolean {
  return peer.ssh !== null && peer.ssh.direction !== "inbound";
}
function fromPersonalVm(
  machine: MachineBinding | null,
  locale: Locale,
): readonly Text[] {
  const reachable = (machine?.relationships?.peers ?? []).filter(
    reachesOverSsh,
  );
  return [
    t("## Z téhle osobní VM", "## From this personal VM"),
    ...(reachable.length === 0
      ? [
          t(
            "Handover neuvádí žádný peer, na který odsud smíš přes SSH; žádný nehledej a řekni to Principálovi.",
            "The handover records no peer this Machine may reach over SSH; do not look for one, tell the Principal.",
          ),
        ]
      : [
          t(
            "Peers, na které odsud smíš přes SSH, přesně jak je zaznamenal handover:",
            "Peers this Machine may reach over SSH, exactly as the handover records them:",
          ),
          ...reachable.map((peer) => same(peerLine(peer, locale))),
        ]),
    t(
      "- Dosažitelnost rozhoduje Headscale a není to identita ani mandát: handover nezaznamenává, čí peer je. Než na peeru začneš pracovat nebo ovládat zařízení, potvrď s Principálem, že je jeho nebo že je přiřazený jemu.",
      "- Reachability is decided by Headscale and is neither identity nor mandate: the handover does not record whose a peer is. Before you work on a peer or operate a device, confirm with the Principal that it is theirs or assigned to them.",
    ),
    t(
      "- Práce v Organizaci (kód, repozitáře, běhy) patří na pracovní VM, kterou ti Principál potvrdí jako přiřazenou jemu, nikdy na tuhle Mašinu: připoj se přes SSH a pracuj tam. Repozitář Organizace sem nikdy neklonuj.",
      "- Organization work (code, repositories, runs) belongs on a work VM the Principal confirms is assigned to them, never on this Machine: connect over SSH and work there. Never clone an Organization repository onto this personal VM.",
    ),
    t(
      "- Co potřebuje Principálovo vlastní zařízení, například přihlášený prohlížeč, se dělá přes SSH na zařízení, které ti Principál potvrdí jako své.",
      "- What needs the Principal's own device, for example the signed-in browser, is done over SSH on a device the Principal confirms is theirs.",
    ),
    t(
      "- Žádná pracovní Mašina na tuhle osobní VM nikdy nesmí (decision 0155); cestu zpět neotevírej.",
      "- No work Machine ever reaches this personal VM (decision 0155); do not open a way back.",
    ),
  ];
}

function thisMachine(source: InstructionSource): string {
  const { preset, machine } = source;
  const { locale } = source.profile;
  const relationships = machine?.relationships;
  const entry = machine?.entry;
  return document(
    locale,
    t("Tahle Mašina", "This Machine"),
    `${generated[locale]}; ${JSON.stringify({ preset })}`,
    [
      t(
        "## Identita podle zaznamenaného handoveru",
        "## Identity, from the recorded handover",
      ),
      ...identitySection(preset, machine, locale).map(same),
      ...(entry
        ? [
            t(
              `- Vstup: Launchpad téhle Mašiny je dosažitelný na \`${entry.externalOrigin}\` přes bránu Organizace (decision F16); přihlášení řeší brána a Launchpad poslouchá za ní jen na loopback portu ${entry.listenPort}.`,
              `- Entry: this Machine's Launchpad is reached at \`${entry.externalOrigin}\` through the Organization's gateway (decision F16); admission is the gateway's, and the Launchpad listens only on loopback port ${entry.listenPort} behind it.`,
            ),
          ]
        : []),
      blank,
      t(
        `## Preset \`${preset}\` (verze ${presetVersion})`,
        `## Preset \`${preset}\` (version ${presetVersion})`,
      ),
      presetMeaning[preset],
      blank,
      t(
        "## Zóny: co kam smí (decision 0155)",
        "## Zones: what may reach what (decision 0155)",
      ),
      t(
        "Mašiny a klienti jednoho Operátora tvoří dvě zóny. **Osobní zóna** zahrnuje Principálovy osobní klienty (laptop, telefon) a jeho jedinou osobní VM; jejím Ownerem je Principál. **Pracovní zóna** zahrnuje pracovní VM přiřazené tomuhle Operátorovi (klidně několik, napříč Organizacemi téhož Conglomerate) a pracovní laptop vydaný Organizací; jejím Ownerem je Organizace. Zóna se řídí poli `owner` a `operator`, obě svázaná s neměnnými GitHub ID, nikdy Headscale uživatelem ani jménem.",
        "One operator's Machines and clients form two zones. The **personal zone** holds the Principal's personal clients (laptop, phone) and their one personal VM; its Owner is the Principal. The **work zone** holds the work VMs assigned to this operator (possibly several, across Organizations of the same Conglomerate) and a work laptop issued by an Organization; its Owner is the Organization. The zone follows `owner` and `operator`, both bound to immutable GitHub IDs, never a Headscale user or a name.",
      ),
      blank,
      t(
        "- Uvnitř zóny oběma směry: osobní klient ↔ osobní VM; pracovní laptop ↔ pracovní VM téže Organizace přiřazená témuž Operátorovi. Pracovní VM mezi sebou žádný grant nemají, ani v rámci jedné Organizace.",
        "- Inside a zone, both directions: personal client ↔ personal VM; work laptop ↔ work VM of the same Organization assigned to the same operator. Work VMs have no grant between each other, not even within one Organization.",
      ),
      t(
        "- Z osobní do pracovní: ano. Osobní klienti a osobní VM smějí na každou pracovní VM téhož Operátora (SSH i HTTPS).",
        "- From personal to work: yes. Personal clients and the personal VM reach every work VM of the same operator (SSH and HTTPS).",
      ),
      t(
        "- Z pracovní do osobní: nikdy. Žádná pracovní VM ani pracovní laptop nemá grant na osobní VM ani osobní laptop.",
        "- From work to personal: never. No work VM or work laptop has a grant to a personal VM or a personal laptop.",
      ),
      t(
        "- Sdílená team VM přijímá jen příchozí spojení od členů živého GitHub Teamu, ke kterému je svázaná (decisions 0147/0149), a nikdy nemá odchozí grant.",
        "- A shared team VM accepts only inbound connections from members of the live GitHub Team it is bound to (decisions 0147/0149) and never has an outbound grant.",
      ),
      t(
        "- Mezi Principály nic implicitně. Telefon není SSH server.",
        "- Nothing implicitly between Principals. A phone is not an SSH server.",
      ),
      t(
        "- Všechno platí uvnitř jednoho Conglomerate (jednoho Headscale tailnetu); osobní VM je node jen svého domovského tailnetu a mezi tailnety se žádný most nestaví.",
        "- Everything holds inside one Conglomerate (one Headscale tailnet); a personal VM is a node of its home tailnet only, and no bridge is built between tailnets.",
      ),
      t(
        "- Správa Conglomerate Hostu patří Ownerovi Organizace, která ho vlastní, a jen z jeho osobního laptopu a osobní VM.",
        "- Administration of the Conglomerate Host belongs to the Owner of the Organization that owns it, only from their personal laptop and personal VM.",
      ),
      blank,
      t(
        `**Zóna téhle Mašiny.** ${zoneOfThisMachine(preset, machine).cs}`,
        `**This Machine's zone.** ${zoneOfThisMachine(preset, machine).en}`,
      ),
      blank,
      t("## Hranice na téhle Mašině", "## Boundaries on this Machine"),
      ...boundaries(preset),
      ...(relationships === undefined
        ? []
        : [
            blank,
            t("## Vztahy", "## Relationships"),
            t(
              `Peers téhle Mašiny v tailnetu, jak je handover odvozuje z grantů Conglomerate Hostu (tahle Mašina je v ${relationships.zone === "personal" ? "osobní" : "pracovní"} zóně): kam tahle Mašina smí a kdo smí na ni, u každého peeru jeho druh, zóna, Organizace, SSH host, účet a směr a HTTPS hostnames gateway dostupné odsud.`,
              `This Machine's tailnet peers as the handover records them from the Conglomerate Host grants (this Machine is in the ${relationships.zone} zone): what this Machine may reach and what may reach it, per peer with its kind, zone, Organization, SSH host, account and direction, and the HTTPS gateway hostnames reachable from here.`,
            ),
            ...relationships.peers.map((peer) => same(peerLine(peer, locale))),
            t(
              "Nic z toho Lazurio nevynucuje: vynucuje to Headscale policy Conglomerate Hostu a transport není autentizace, takže SSH klíče i přihlášení do aplikací zůstávají samostatné.",
              "Lazurio enforces none of this: the Headscale policy of the Conglomerate Host does, and transport is not authentication, so SSH keys and application sign-in stay separate.",
            ),
          ]),
      ...(machine === null ? [] : [blank, ...sshRules]),
      ...(preset === "hosted-personal"
        ? [blank, ...fromPersonalVm(machine, locale)]
        : []),
    ],
  );
}

// Every manual file for this Folder, keyed by its path, in the Folder's
// locale. The file names are the same in both locales.
export function renderManual(
  input: unknown,
): Readonly<Record<ManualPath, string>> {
  const source = parseInstructionSource(input);
  const { locale } = source.profile;
  const note = generated[locale];
  const titled = (title: Text, body: readonly Text[]) =>
    document(locale, title, note, body);
  return Object.freeze({
    "manual/lazurio.md": titled(same("Lazurio"), lazurio),
    "manual/this-machine.md": thisMachine(source),
    "manual/working-here.md": titled(
      t("Jak se tu pracuje", "Working here"),
      workingHere,
    ),
    "manual/roles.md": titled(t("Role", "Roles"), roles),
    "manual/glossary.md": titled(t("Slovník", "Glossary"), glossary),
    "manual/troubleshooting.md": titled(
      t("Řešení problémů", "Troubleshooting"),
      troubleshooting(source.preset),
    ),
  });
}
